import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import {
  Zap,
  LogIn,
  Search,
  ArrowLeft,
  BarChart3,
  Star,
  Users,
  Shield,
  MessageCircle,
  Target,
  Gift,
  Gamepad2,
  BookOpen,
  Settings,
  FileText,
  Clock,
  HelpCircle,
  ChevronRight,
} from 'lucide-react';

/* ───────── FAQ Data ───────── */

interface FAQItem {
  q: string;
  a: string;
}

interface FAQSection {
  title: string;
  icon: React.ElementType;
  items: FAQItem[];
}

const faqSections: FAQSection[] = [
  {
    title: 'Getting Started',
    icon: BookOpen,
    items: [
      {
        q: 'How do I log in to Beacon?',
        a: 'Navigate to the sign-in page and enter your email and password. If your administrator has set up your account, you\'ll be taken directly to your Classroom view. If you don\'t have an account yet, ask your BCBA or admin for an invite code.',
      },
      {
        q: 'What is an invite code and how do I use it?',
        a: 'An invite code is a one-time or multi-use code generated by your administrator. Go to the Join page, enter the code, and your account will automatically be linked to the correct agency, classroom, and role. You\'ll have access to all the students assigned to you.',
      },
      {
        q: 'I logged in but see "Access Not Configured" — what do I do?',
        a: 'This means your account hasn\'t been linked to an agency yet. Ask your administrator or BCBA to add your email to the system and assign you to the correct agency and app. Then click the Retry button on the blocked screen.',
      },
      {
        q: 'Can I use Beacon on my phone?',
        a: 'Yes! Beacon is a Progressive Web App (PWA). On your phone, open the app in your browser, then tap "Add to Home Screen" from the browser menu. It will look and feel like a native app with offline support.',
      },
      {
        q: 'How do I install the app on my device?',
        a: 'Visit the Install page from the Settings menu. Follow the step-by-step instructions for your device (iOS or Android). The app installs directly from your browser — no app store needed.',
      },
    ],
  },
  {
    title: 'Classroom View',
    icon: Users,
    items: [
      {
        q: 'What is the Classroom View?',
        a: 'The Classroom View is your home screen. It shows all students in your classroom with their attendance status, current location/presence, assigned staff, and live Beacon Point balances. You can take attendance, update presence, and access Quick Actions all from this single screen.',
      },
      {
        q: 'How do I take attendance?',
        a: 'From the Classroom View, tap any student\\'s attendance indicator (the colored dot). Select "Present," "Absent," "Tardy," or "Early Dismissal." The change saves instantly and is visible to your entire team.',
      },
      {
        q: 'What is student presence vs. attendance?',
        a: 'Attendance tracks whether a student is in school for the day (Present/Absent/Tardy). Presence tracks where they are right now — in the classroom, at a pull-out, in the bathroom, etc. You can update presence throughout the day without changing attendance.',
      },
      {
        q: 'How do I assign staff to students?',
        a: 'In the Classroom View, tap on a student\\'s staff assignment area. Select the available staff member from the dropdown. This updates in real time so your whole team knows who is paired with whom.',
      },
      {
        q: 'What are the "Who\\'s Here" and "Staff Presence" panels?',
        a: '"Who\\'s Here" shows a quick count of present vs. absent students with visual indicators. "Staff Presence" shows which staff members are in the room, on break, or at a different location. Both update in real time.',
      },
    ],
  },
  {
    title: 'Data Collection',
    icon: BarChart3,
    items: [
      {
        q: 'What types of data can I collect?',
        a: 'Beacon supports four data types: Frequency (counting occurrences), Duration (timing how long something lasts), ABC (Antecedent-Behavior-Consequence logs), and Engagement Sampling (on-task/off-task checks at intervals). Each type is designed for one-tap logging.',
      },
      {
        q: 'How does Quick Add work?',
        a: 'Quick Add is a one-tap counter for common behaviors. Select a student, choose a behavior from their configured list, and tap the + button. Each tap records one occurrence with a timestamp. You can also use the - button if you need to correct a count.',
      },
      {
        q: 'How do I log an ABC entry?',
        a: 'From the Data Collection page, select a student and tap "ABC Log." Fill in the Antecedent (what happened before), Behavior (what the student did), and Consequence (what happened after). You can also add intensity, duration, and notes. Everything is saved with a timestamp.',
      },
      {
        q: 'What are Engagement Prompts?',
        a: 'Engagement Prompts are timed reminders that pop up at intervals you set (e.g., every 5 minutes). When the prompt appears, you simply tap whether the student is "On Task" or "Off Task." This builds a rich dataset for your BCBA without interrupting instruction.',
      },
      {
        q: 'Can I collect data for multiple students at once?',
        a: 'Yes! The Bulk Award panel lets you award points to multiple or all students simultaneously. For individual data like ABC logs, you can quickly switch between students using the student selector.',
      },
      {
        q: 'What happens to the data I collect?',
        a: 'All data is saved instantly to the cloud. Your BCBA can view it in real time, and it automatically feeds into weekly trend charts and summary reports. You never have to manually transfer or email data.',
      },
      {
        q: 'Can a substitute teacher collect data?',
        a: 'Yes! Teachers can generate a Guest Access Code from the Classroom Manager. The substitute enters this code on any device — no login needed. They can collect frequency and duration data for the assigned classroom.',
      },
    ],
  },
  {
    title: 'Engagement & Skill Probes',
    icon: Target,
    items: [
      {
        q: 'What is Engagement Sampling?',
        a: 'Engagement Sampling uses timed intervals to check whether a student is on-task or off-task. You set the interval (e.g., every 3 minutes), and Beacon prompts you to record. Over time, this builds percentage-based engagement data that\'s invaluable for BCBAs.',
      },
      {
        q: 'What are Skill Probes?',
        a: 'Skill Probes let you quickly test a student on specific IEP targets during instruction. Select the skill, mark whether they demonstrated it independently, with prompting, or not at all. Results feed directly into progress monitoring.',
      },
      {
        q: 'Can I snooze a prompt?',
        a: 'Yes! If you\\'re in the middle of a critical teaching moment, tap "Snooze" on any engagement prompt. It will come back after a configurable delay (default 2 minutes). This ensures data collection doesn\\'t interfere with instruction.',
      },
      {
        q: 'How do interval settings work?',
        a: 'Go to Settings or ask your BCBA to configure intervals. You can set the interval length (1-30 minutes), active hours, specific days, and whether prompts are student-specific or classroom-wide.',
      },
    ],
  },
  {
    title: 'Beacon Points™',
    icon: Star,
    items: [
      {
        q: 'What are Beacon Points?',
        a: 'Beacon Points are a real-time token economy system. Students earn points for positive behaviors, engagement, and completing tasks. Points can be spent in the Reward Store. The system supports auto-awarding, manual awards, and response cost (point deductions).',
      },
      {
        q: 'How do students earn points?',
        a: 'Points can be earned three ways: (1) Automatically — when you log data events like engagement checks or frequency counts, matching point rules auto-award points. (2) Manually — tap the + button on any student to award bonus points. (3) Bulk Awards — award points to your entire class at once.',
      },
      {
        q: 'What is Response Cost?',
        a: 'Response Cost is a behavior management strategy where points are deducted for specific behaviors. It must be explicitly enabled per student by the BCBA. When enabled, certain logged behaviors will automatically deduct the configured number of points.',
      },
      {
        q: 'How do Token Boards work?',
        a: 'Token Boards visualize a student\\'s progress toward a point goal. As they earn points, tokens fill up on their board. When all tokens are filled, the student has reached their goal! Token boards are displayed on the Classroom Board for the whole class to see.',
      },
      {
        q: 'Can I reset points?',
        a: 'Yes. You can reset points for individual students or the entire class. This is typically done at the start of a new day or session. Go to the Beacon Points controls and select "Reset" for the student or class.',
      },
      {
        q: 'How do Point Rules work?',
        a: 'Point Rules are configured by administrators. They define how many points are awarded (or deducted) for specific events. For example: "+2 points for every on-task engagement check" or "-1 point for physical aggression." Rules can be linked to specific data types.',
      },
    ],
  },
  {
    title: 'Reward Store',
    icon: Gift,
    items: [
      {
        q: 'What is the Reward Store?',
        a: 'The Reward Store is where students spend their Beacon Points. Teachers create rewards with point costs, categories (tangible, activity, social, edible), stock limits, and images. Students can browse and redeem rewards from the Student Portal or classroom board.',
      },
      {
        q: 'How do I create a reward?',
        a: 'Go to the Rewards page and tap "Add Reward." Enter a name, point cost, category, and optional description. You can set stock limits to prevent over-redemption. Rewards appear immediately in the store.',
      },
      {
        q: 'What are Sponsored Rewards?',
        a: 'Sponsored Rewards are special items added by administrators or partners. They appear alongside your classroom rewards with a "Sponsored" badge. They\\'re a great way to add exciting options without spending classroom budget.',
      },
      {
        q: 'Can students redeem rewards themselves?',
        a: 'Yes! Through the Student Portal, students can browse available rewards and request redemption. Teachers receive a notification and approve or deny the request. This builds student autonomy and self-management skills.',
      },
    ],
  },
  {
    title: 'Game Board & Avatars',
    icon: Gamepad2,
    items: [
      {
        q: 'What is the Game Board?',
        a: 'The Game Board is a visual display designed for smartboard projection. It shows a race track where each student\\'s avatar advances based on their points. It includes a class leaderboard, class-wide goal tracker, and the Word of the Week.',
      },
      {
        q: 'How do avatars work?',
        a: 'Each student selects a starting avatar. As they earn more points, they unlock new avatar options. This gamification element motivates students to stay engaged and earn more points throughout the day.',
      },
      {
        q: 'Can I project the Game Board on a smartboard?',
        a: 'Absolutely! Open the board URL (e.g., /board/your-classroom-slug) on any browser connected to your smartboard. It updates in real time — no refreshing needed. Students love watching their avatars move!',
      },
      {
        q: 'How do class goals work?',
        a: 'Set a class-wide point goal (e.g., "Class earns 500 points today"). The Game Board shows a progress bar filling up as the whole class earns points together. When they hit the goal, celebrate with a class reward!',
      },
    ],
  },
  {
    title: 'Communication',
    icon: MessageCircle,
    items: [
      {
        q: 'What are Threads?',
        a: 'Threads are team-based message channels. Create public threads for your whole classroom team or private threads for specific staff members. Use them for daily updates, incident reports, and quick coordination.',
      },
      {
        q: 'What is the Inbox?',
        a: 'The Inbox is for more formal, structured messages between staff. Messages can include attachments, be pinned to specific students, and be flagged for follow-up. It\\'s designed for communication that needs to be referenced later.',
      },
      {
        q: 'What are Parent Snapshots?',
        a: 'Parent Snapshots are secure, read-only links you can send to families. They show a student\\'s daily highlights — points earned, positive behaviors, and classroom activity. Parents view them in their browser without needing an account.',
      },
      {
        q: 'How do I send a Parent Snapshot?',
        a: 'From the student\\'s detail page, tap "Parent Snapshot." Beacon generates a secure, time-limited link. Share it via text, email, or your school\\'s parent communication platform. The link expires after the set period.',
      },
      {
        q: 'Can parents respond to messages?',
        a: 'Parent Snapshots are read-only to keep the focus on positive communication. For two-way communication, your school may use the Behavior Decoded parent companion app, which integrates with Beacon.',
      },
    ],
  },
  {
    title: 'Safety & Mayday',
    icon: Shield,
    items: [
      {
        q: 'What is the MAYDAY button?',
        a: 'The MAYDAY button is an emergency alert system. Press it to instantly notify your supervisors and admin team that you need support. You can select urgency level, specific recipients, and add a quick note about the situation.',
      },
      {
        q: 'Who receives MAYDAY alerts?',
        a: 'MAYDAY alerts go to all configured Mayday Contacts for your agency. These typically include BCBAs, program directors, and on-call supervisors. Administrators configure the contact list in the Mayday Contacts Manager.',
      },
      {
        q: 'What urgency levels are available?',
        a: 'There are three levels: "Urgent" (immediate physical safety concern), "High" (escalating situation needing prompt support), and "Standard" (non-emergency support request). Each level triggers appropriate notification priority.',
      },
      {
        q: 'Can I cancel a MAYDAY alert?',
        a: 'Yes. After sending, you can resolve or cancel the alert from the same interface. This updates all recipients immediately. However, the alert is logged for safety documentation purposes.',
      },
    ],
  },
  {
    title: 'IEP Tools',
    icon: FileText,
    items: [
      {
        q: 'What is the IEP Reader?',
        a: 'The IEP Reader lets you upload IEP documents (PDF). Beacon uses AI to extract goals, accommodations, services, and progress data. Everything is parsed into structured, searchable cards that you can review and approve.',
      },
      {
        q: 'What is the IEP Writer?',
        a: 'The IEP Writer helps generate IEP goals, FBA narratives, and BIP documents using AI. It pulls from the student\\'s collected data to suggest evidence-based goals and interventions tailored to their needs.',
      },
      {
        q: 'Do I need to be a BCBA to use the IEP tools?',
        a: 'No! Teachers can upload IEPs and view extracted information. However, approving extracted goals and generating clinical documents is typically reserved for BCBAs and supervisors based on your agency\\'s configuration.',
      },
    ],
  },
  {
    title: 'Classroom Management',
    icon: Settings,
    items: [
      {
        q: 'How do I set up a new classroom?',
        a: 'Go to the Classroom Manager (from the More menu). Tap "Create Classroom" and enter a name, school, and grade band. Then add students and assign staff members with their roles (Teacher, BI, Aide, BCBA, etc.).',
      },
      {
        q: 'Can I be assigned to multiple classrooms?',
        a: 'Yes! Staff can be assigned to multiple classroom groups. Use the classroom selector to switch between them. Your data and settings are maintained separately for each classroom.',
      },
      {
        q: 'How do I add students to my classroom?',
        a: 'In the Classroom Manager, select your classroom and tap "Add Students." Choose from the students assigned to your agency. Students can be in multiple classrooms simultaneously.',
      },
      {
        q: 'What staff roles are available?',
        a: 'Beacon supports multiple staff roles: Teacher, Behavior Interventionist (BI), Aide, BCBA, SPED, SLP, OT, and Other. Each staff member is identified by their role badge in the classroom view.',
      },
      {
        q: 'How do Guest Access Codes work?',
        a: 'Guest Access Codes are temporary, time-limited codes for substitute teachers or visiting staff. Generate one from the Classroom Manager, share it, and the guest can collect data without creating an account. Codes expire automatically.',
      },
    ],
  },
  {
    title: 'Reports & Data',
    icon: BarChart3,
    items: [
      {
        q: 'What reports are available?',
        a: 'Beacon generates Weekly Data Summaries (auto-generated trend charts), Parent Reports (shareable family-friendly summaries), and detailed data exports. All reports pull from your real-time data — no manual compilation needed.',
      },
      {
        q: 'How do Weekly Trend Charts work?',
        a: 'Trend Charts automatically graph your collected data over time. They show frequency trends, duration averages, engagement percentages, and ABC patterns. Your BCBA uses these to make data-driven decisions.',
      },
      {
        q: 'Can I export data?',
        a: 'Data can be viewed in-app through summaries and trend charts. For detailed exports, your BCBA or administrator can access the full data through the admin dashboard.',
      },
    ],
  },
  {
    title: 'Account & Settings',
    icon: Settings,
    items: [
      {
        q: 'How do I change my notification settings?',
        a: 'Go to Settings → Notifications. You can toggle engagement prompts, data log reminders, escalation alerts, caregiver messages, and admin alerts. You can also set quiet hours so you don\\'t receive notifications outside school hours.',
      },
      {
        q: 'How do I reset my password?',
        a: 'From the login page, tap "Forgot Password." Enter your email and you\\'ll receive a reset link. Follow the link to set a new password.',
      },
      {
        q: 'Can I switch between agencies or workspaces?',
        a: 'If you belong to multiple agencies, you\\'ll see a Workspace Selector when you log in. Choose the agency you want to work in. You can switch anytime from the Settings page.',
      },
      {
        q: 'What data can my BCBA see?',
        a: 'Your BCBA can see all data you collect — frequency counts, duration logs, ABC entries, engagement checks, and skill probes. They also see trend charts and can generate clinical reports. They cannot see your personal settings or notifications.',
      },
    ],
  },
];

/* ───────── Tutorial Steps ───────── */

interface TutorialStep {
  step: number;
  title: string;
  description: string;
  icon: React.ElementType;
}

interface TutorialSection {
  title: string;
  description: string;
  steps: TutorialStep[];
}

const tutorials: TutorialSection[] = [
  {
    title: 'Your First Day with Beacon',
    description: 'A step-by-step guide to get through your first school day using Beacon.',
    steps: [
      { step: 1, title: 'Sign in & check your Classroom', description: 'Log in and navigate to the Classroom View. You\'ll see your assigned students, their attendance from yesterday, and any staff notes.', icon: Users },
      { step: 2, title: 'Take morning attendance', description: 'Tap each student\'s attendance indicator to mark them Present, Absent, or Tardy. This takes about 30 seconds for a full class.', icon: Clock },
      { step: 3, title: 'Start data collection', description: 'Open Quick Add for your first student. Tap the behavior buttons as you observe them during morning routine. Each tap is timestamped automatically.', icon: BarChart3 },
      { step: 4, title: 'Award Beacon Points', description: 'When students follow routines, award points manually with one tap or let auto-rules handle it. Watch token boards fill up on the projected Game Board.', icon: Star },
      { step: 5, title: 'Check engagement prompts', description: 'If your BCBA has set up interval prompts, they\'ll pop up during instruction. Just tap On Task or Off Task — it takes 2 seconds.', icon: Target },
      { step: 6, title: 'Send a Parent Snapshot', description: 'At the end of the day, generate a Parent Snapshot link for any student. Share via text — families love seeing the positive highlights!', icon: MessageCircle },
    ],
  },
  {
    title: 'Setting Up Your Classroom',
    description: 'How to configure your classroom for the first time.',
    steps: [
      { step: 1, title: 'Create your classroom group', description: 'Go to Classroom Manager from the More menu. Tap "Create Classroom" and enter a name (e.g., "Room 12 — Ms. Rivera"), school name, and grade band.', icon: Users },
      { step: 2, title: 'Add students', description: 'Select your classroom and tap "Add Students." Pick students from your agency roster. Students appear in your Classroom View immediately.', icon: BookOpen },
      { step: 3, title: 'Assign staff', description: 'Add yourself and any co-teachers, BIs, or aides. Select the correct role for each person — this shows as a badge in the classroom.', icon: Users },
      { step: 4, title: 'Configure the Game Board', description: 'Go to Board Settings and set your classroom slug, mission text, word of the week, and class goal. Project the board URL on your smartboard.', icon: Gamepad2 },
      { step: 5, title: 'Set up rewards', description: 'Go to the Rewards page and add at least 3-5 rewards with different point costs. Include a mix of tangible, activity, and social rewards.', icon: Gift },
    ],
  },
  {
    title: 'Running an Effective Data Day',
    description: 'Best practices for consistent, high-quality data collection.',
    steps: [
      { step: 1, title: 'Check your targets', description: 'Review which behaviors and skills you\'re tracking today. Your BCBA sets these up, but you can see them in the Target Manager.', icon: Target },
      { step: 2, title: 'Use Quick Add for frequency', description: 'For behaviors that happen frequently (hand-raising, task refusal), keep Quick Add open. One tap per occurrence. The app counts automatically.', icon: BarChart3 },
      { step: 3, title: 'Time durations when needed', description: 'For behaviors with duration (tantrums, time-on-task), use the timer. Tap start when it begins, stop when it ends. Beacon records the exact seconds.', icon: Clock },
      { step: 4, title: 'Log ABC for significant incidents', description: 'When a notable behavior occurs, log the full ABC. This gives your BCBA the context they need for functional analysis.', icon: FileText },
      { step: 5, title: 'Respond to engagement prompts', description: 'When prompted, take a quick scan of the student and tap On Task or Off Task. Consistency is more important than perfection.', icon: Target },
      { step: 6, title: 'End-of-day review', description: 'Check the data summary to make sure you haven\'t missed anything. Add any notes while the day is fresh in your mind.', icon: BookOpen },
    ],
  },
];

/* ───────── Component ───────── */

const FAQTutorial = () => {
  const navigate = useNavigate();
  const [search, setSearch] = useState('');
  const [activeTab, setActiveTab] = useState<'faq' | 'tutorials'>('faq');

  const filteredSections = faqSections
    .map((section) => ({
      ...section,
      items: section.items.filter(
        (item) =>
          item.q.toLowerCase().includes(search.toLowerCase()) ||
          item.a.toLowerCase().includes(search.toLowerCase())
      ),
    }))
    .filter((section) => section.items.length > 0);

  const totalQuestions = faqSections.reduce((sum, s) => sum + s.items.length, 0);

  return (
    <div className="min-h-screen bg-gradient-to-b from-background via-background to-muted/30">
      {/* Top bar */}
      <div className="sticky top-0 z-50 bg-card/80 backdrop-blur-md border-b border-border/50">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="icon" onClick={() => navigate('/tour')} className="shrink-0">
              <ArrowLeft className="h-4 w-4" />
            </Button>
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <Zap className="h-4 w-4 text-primary-foreground" />
            </div>
            <span className="font-bold text-foreground text-lg">Beacon</span>
            <Badge variant="secondary" className="text-[10px] ml-1">Help Center</Badge>
          </div>
          <Button size="sm" onClick={() => navigate('/login')} className="gap-1.5">
            <LogIn className="h-4 w-4" />
            <span>Sign In</span>
          </Button>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8 space-y-8">
        {/* Header */}
        <div className="text-center space-y-3">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary text-xs font-medium">
            <HelpCircle className="h-3.5 w-3.5" />
            {totalQuestions} questions answered
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-foreground">
            FAQ & Tutorials
          </h1>
          <p className="text-muted-foreground text-base max-w-xl mx-auto">
            Everything you need to know about using Beacon in your classroom — from first login to advanced features.
          </p>
        </div>

        {/* Tab toggle */}
        <div className="flex items-center justify-center gap-1 p-1 bg-muted rounded-xl w-fit mx-auto">
          <button
            onClick={() => setActiveTab('faq')}
            className={`px-5 py-2 rounded-lg text-sm font-medium transition-all ${
              activeTab === 'faq'
                ? 'bg-card text-foreground shadow-sm'
                : 'text-muted-foreground hover:text-foreground'
            }`}
          >
            <HelpCircle className="h-4 w-4 inline mr-1.5 -mt-0.5" />
            FAQ
          </button>
          <button
            onClick={() => setActiveTab('tutorials')}
            className={`px-5 py-2 rounded-lg text-sm font-medium transition-all ${
              activeTab === 'tutorials'
                ? 'bg-card text-foreground shadow-sm'
                : 'text-muted-foreground hover:text-foreground'
            }`}
          >
            <BookOpen className="h-4 w-4 inline mr-1.5 -mt-0.5" />
            Tutorials
          </button>
        </div>

        {activeTab === 'faq' && (
          <>
            {/* Search */}
            <div className="relative max-w-md mx-auto">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search questions…"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="pl-10"
              />
            </div>

            {/* Quick category jump */}
            {!search && (
              <div className="flex flex-wrap items-center justify-center gap-2">
                {faqSections.map((section) => {
                  const SIcon = section.icon;
                  return (
                    <a
                      key={section.title}
                      href={`#faq-${section.title.toLowerCase().replace(/\s+/g, '-')}`}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium bg-muted text-muted-foreground hover:bg-muted/80 transition-all"
                    >
                      <SIcon className="h-3.5 w-3.5" />
                      {section.title}
                    </a>
                  );
                })}
              </div>
            )}

            {/* FAQ sections */}
            <div className="space-y-6">
              {filteredSections.map((section) => {
                const SIcon = section.icon;
                return (
                  <div
                    key={section.title}
                    id={`faq-${section.title.toLowerCase().replace(/\s+/g, '-')}`}
                    className="scroll-mt-20"
                  >
                    <div className="flex items-center gap-2 mb-3">
                      <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                        <SIcon className="h-4 w-4 text-primary" />
                      </div>
                      <h2 className="text-lg font-semibold text-foreground">{section.title}</h2>
                      <Badge variant="outline" className="text-[10px] ml-auto">
                        {section.items.length} {section.items.length === 1 ? 'question' : 'questions'}
                      </Badge>
                    </div>
                    <Card className="border-border/50">
                      <CardContent className="p-0">
                        <Accordion type="multiple" className="w-full">
                          {section.items.map((item, i) => (
                            <AccordionItem
                              key={i}
                              value={`${section.title}-${i}`}
                              className="border-border/30 last:border-b-0"
                            >
                              <AccordionTrigger className="px-4 py-3 text-sm font-medium text-foreground hover:no-underline text-left">
                                {item.q}
                              </AccordionTrigger>
                              <AccordionContent className="px-4 pb-4 text-sm text-muted-foreground leading-relaxed">
                                {item.a}
                              </AccordionContent>
                            </AccordionItem>
                          ))}
                        </Accordion>
                      </CardContent>
                    </Card>
                  </div>
                );
              })}

              {filteredSections.length === 0 && (
                <div className="text-center py-12">
                  <HelpCircle className="h-10 w-10 text-muted-foreground/30 mx-auto mb-3" />
                  <p className="text-muted-foreground">No questions match "{search}"</p>
                  <Button variant="link" size="sm" onClick={() => setSearch('')} className="mt-1">
                    Clear search
                  </Button>
                </div>
              )}
            </div>
          </>
        )}

        {activeTab === 'tutorials' && (
          <div className="space-y-8">
            {tutorials.map((tutorial, tIdx) => (
              <Card key={tIdx} className="border-border/50 overflow-hidden">
                <div className="p-6 border-b border-border/30 bg-muted/30">
                  <div className="flex items-start gap-3">
                    <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0 mt-0.5">
                      <BookOpen className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-foreground">{tutorial.title}</h3>
                      <p className="text-sm text-muted-foreground mt-0.5">{tutorial.description}</p>
                    </div>
                  </div>
                </div>
                <CardContent className="p-0">
                  {tutorial.steps.map((step, sIdx) => {
                    const StepIcon = step.icon;
                    return (
                      <div
                        key={sIdx}
                        className="flex items-start gap-4 px-6 py-4 border-b border-border/20 last:border-b-0"
                      >
                        <div className="shrink-0 flex flex-col items-center gap-1">
                          <div className="w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-sm font-bold">
                            {step.step}
                          </div>
                          {sIdx < tutorial.steps.length - 1 && (
                            <div className="w-px h-full min-h-[16px] bg-border/40" />
                          )}
                        </div>
                        <div className="pt-1">
                          <div className="flex items-center gap-2 mb-1">
                            <StepIcon className="h-4 w-4 text-primary/70" />
                            <h4 className="text-sm font-semibold text-foreground">{step.title}</h4>
                          </div>
                          <p className="text-sm text-muted-foreground leading-relaxed">
                            {step.description}
                          </p>
                        </div>
                      </div>
                    );
                  })}
                </CardContent>
              </Card>
            ))}
          </div>
        )}

        {/* Bottom CTA */}
        <div className="text-center py-6 space-y-3 border-t border-border/30">
          <p className="text-muted-foreground text-sm">
            Still have questions? Your BCBA or administrator can help.
          </p>
          <div className="flex items-center justify-center gap-3">
            <Button variant="outline" onClick={() => navigate('/tour')} className="gap-1.5">
              <ArrowLeft className="h-4 w-4" />
              Back to Tour
            </Button>
            <Button onClick={() => navigate('/login')} className="gap-1.5">
              <LogIn className="h-4 w-4" />
              Sign In
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FAQTutorial;
