import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible';
import {
  Zap, LogIn, Search, ArrowLeft, BarChart3, Star, Users, Shield,
  MessageCircle, Target, Gift, Gamepad2, BookOpen, Settings, FileText,
  Clock, HelpCircle, ChevronRight, ChevronDown, GraduationCap, UserCog,
  Heart, CheckCircle2, Circle, Megaphone, Eye, Smartphone, Bell,
  AlertTriangle, LayoutDashboard, UserPlus, Send, TrendingUp, Play,
  Wrench, Flame, Lightbulb, Zap as ZapIcon,
} from 'lucide-react';

/* ═══════════════════════════════════════════════════════════ */
/*  FAQ DATA                                                  */
/* ═══════════════════════════════════════════════════════════ */

interface FAQItem { q: string; a: string }
interface FAQSection { title: string; icon: React.ElementType; items: FAQItem[] }

const faqSections: FAQSection[] = [
  {
    title: 'Getting Started',
    icon: BookOpen,
    items: [
      { q: 'How do I log in to Beacon?', a: "Navigate to the sign-in page and enter your email and password. If your administrator has set up your account, you'll be taken directly to your Classroom view. If you don't have an account yet, ask your BCBA or admin for an invite code." },
      { q: 'What is an invite code and how do I use it?', a: "An invite code is a one-time or multi-use code generated by your administrator. Go to the Join page, enter the code, and your account will automatically be linked to the correct agency, classroom, and role." },
      { q: 'I logged in but see "Access Not Configured" — what do I do?', a: "This means your account hasn't been linked to an agency yet. Ask your administrator or BCBA to add your email to the system and assign you to the correct agency and app. Then click the Retry button on the blocked screen." },
      { q: 'Can I use Beacon on my phone?', a: 'Yes! Beacon is a Progressive Web App (PWA). On your phone, open the app in your browser, then tap "Add to Home Screen" from the browser menu. It will look and feel like a native app with offline support.' },
      { q: 'How do I install the app on my device?', a: 'Visit the Install page from the Settings menu. Follow the step-by-step instructions for your device (iOS or Android). The app installs directly from your browser — no app store needed.' },
    ],
  },
  {
    title: 'Classroom View',
    icon: Users,
    items: [
      { q: 'What is the Classroom View?', a: "The Classroom View is your home screen. It shows all students in your classroom with their attendance status, current location/presence, assigned staff, and live Beacon Point balances." },
      { q: 'How do I take attendance?', a: "From the Classroom View, tap any student's attendance indicator (the colored dot). Select Present, Absent, Tardy, or Early Dismissal. The change saves instantly." },
      { q: 'What is student presence vs. attendance?', a: 'Attendance tracks whether a student is in school for the day. Presence tracks where they are right now — in the classroom, at a pull-out, in the bathroom, etc.' },
      { q: 'How do I assign staff to students?', a: "In the Classroom View, tap on a student's staff assignment area. Select the available staff member from the dropdown. This updates in real time." },
      { q: "What are the Who's Here and Staff Presence panels?", a: "Who's Here shows a quick count of present vs. absent students. Staff Presence shows which staff members are in the room, on break, or at a different location. Both update in real time." },
    ],
  },
  {
    title: 'Data Collection',
    icon: BarChart3,
    items: [
      { q: 'What types of data can I collect?', a: 'Beacon supports Frequency (counting occurrences), Duration (timing how long something lasts), ABC (Antecedent-Behavior-Consequence logs), and Engagement Sampling (on-task/off-task checks at intervals).' },
      { q: 'How does Quick Add work?', a: 'Quick Add is a one-tap counter for common behaviors. Select a student, choose a behavior, and tap +. Each tap records one occurrence with a timestamp.' },
      { q: 'How do I log an ABC entry?', a: 'From the Data Collection page, select a student and tap ABC Log. Fill in the Antecedent, Behavior, and Consequence. You can also add intensity, duration, and notes.' },
      { q: 'What are Engagement Prompts?', a: 'Engagement Prompts are timed reminders that pop up at intervals you set. When the prompt appears, simply tap On Task or Off Task.' },
      { q: 'Can I collect data for multiple students at once?', a: 'Yes! The Bulk Award panel lets you award points to multiple students simultaneously. For individual data, quickly switch between students using the selector.' },
      { q: 'What happens to the data I collect?', a: 'All data is saved instantly to the cloud. Your BCBA can view it in real time, and it feeds into weekly trend charts and summary reports.' },
      { q: 'Can a substitute teacher collect data?', a: 'Yes! Generate a Guest Access Code from the Classroom Manager. The substitute enters this code on any device — no login needed.' },
    ],
  },
  {
    title: 'Engagement & Skill Probes',
    icon: Target,
    items: [
      { q: 'What is Engagement Sampling?', a: "Engagement Sampling uses timed intervals to check whether a student is on-task or off-task. Over time, this builds percentage-based engagement data that's invaluable for BCBAs." },
      { q: 'What are Skill Probes?', a: 'Skill Probes let you quickly test a student on specific IEP targets. Mark whether they demonstrated the skill independently, with prompting, or not at all.' },
      { q: 'Can I snooze a prompt?', a: "Yes! Tap Snooze on any engagement prompt. It will come back after a configurable delay. This ensures data collection doesn't interfere with instruction." },
      { q: 'How do interval settings work?', a: 'Go to Settings or ask your BCBA to configure intervals. You can set the interval length (1-30 minutes), active hours, specific days, and scope.' },
    ],
  },
  {
    title: 'Beacon Points\u2122',
    icon: Star,
    items: [
      { q: 'What are Beacon Points?', a: 'Beacon Points are a real-time token economy system. Students earn points for positive behaviors, engagement, and completing tasks. Points can be spent in the Reward Store.' },
      { q: 'How do students earn points?', a: 'Points are earned three ways: (1) Automatically via point rules, (2) Manually with one tap, (3) Bulk Awards for the entire class.' },
      { q: 'What is Response Cost?', a: 'Response Cost deducts points for specific behaviors. It must be enabled per student by the BCBA.' },
      { q: 'How do Token Boards work?', a: "Token Boards visualize a student's progress toward a point goal. As they earn points, tokens fill up on their board." },
      { q: 'Can I reset points?', a: 'Yes. Reset points for individual students or the entire class from the Beacon Points controls.' },
      { q: 'How do Point Rules work?', a: 'Point Rules define how many points are awarded or deducted for specific events. Rules can be linked to specific data types.' },
      { q: 'Can I customize points per behavior?', a: 'Yes. You can adjust point values in the reinforcement settings or assign custom points when logging behavior.' },
    ],
  },
  {
    title: 'Reward Store',
    icon: Gift,
    items: [
      { q: 'What is the Reward Store?', a: 'The Reward Store is where students spend their Beacon Points. Teachers create rewards with point costs, categories, stock limits, and images.' },
      { q: 'How do I create a reward?', a: 'Go to the Rewards page and tap Add Reward. Enter a name, point cost, category, and optional description.' },
      { q: 'What are Sponsored Rewards?', a: 'Sponsored Rewards are special items added by administrators or partners with a Sponsored badge.' },
      { q: 'Can students redeem rewards themselves?', a: 'Yes! Through the Student Portal, students browse and request redemption. Teachers approve or deny the request.' },
      { q: 'Why are rewards not showing?', a: 'Rewards must be active and properly configured. Check the reward store settings and ensure rewards are marked as active.' },
    ],
  },
  {
    title: 'Game Board & Avatars',
    icon: Gamepad2,
    items: [
      { q: 'What is the Game Board?', a: "The Game Board is a visual display for smartboard projection. It shows a race track where each student's avatar advances based on their points." },
      { q: 'How do avatars work?', a: 'Each student selects a starting avatar. As they earn more points, they unlock new avatar options.' },
      { q: 'Can I project the Game Board on a smartboard?', a: 'Absolutely! Open the board URL on any browser connected to your smartboard. It updates in real time.' },
      { q: 'How do class goals work?', a: 'Set a class-wide point goal. The Game Board shows a progress bar filling up as the whole class earns points together.' },
      { q: 'Why is my Game Board not loading?', a: 'This usually happens if no students are assigned to your classroom or the classroom group is not properly set. Make sure students are added and refresh the page.' },
    ],
  },
  {
    title: 'Communication',
    icon: MessageCircle,
    items: [
      { q: 'What are Threads?', a: 'Threads are team-based message channels. Create public threads for your whole classroom team or private threads for specific staff members.' },
      { q: 'What is the Inbox?', a: 'The Inbox is for more formal, structured messages between staff. Messages can include attachments and be pinned to specific students.' },
      { q: 'What are Parent Snapshots?', a: "Parent Snapshots are secure, read-only links showing a student's daily highlights. Parents view them in their browser without needing an account." },
      { q: 'How do I send a Parent Snapshot?', a: "From the student's detail page, tap Parent Snapshot. Share the generated link via text or email." },
      { q: 'Can parents respond to messages?', a: 'Parent Snapshots are read-only. For two-way communication, your school may use the Behavior Decoded parent companion app.' },
      { q: 'Can I message multiple staff at once?', a: 'Yes. Use group threads or @mention multiple users in a message.' },
      { q: 'Why are my threads not updating?', a: 'Threads rely on real-time updates. Try refreshing the page or check your internet connection. If the issue continues, confirm you are in the correct classroom or agency.' },
    ],
  },
  {
    title: 'Safety & Mayday',
    icon: Shield,
    items: [
      { q: 'What is the MAYDAY button?', a: 'The MAYDAY button is an emergency alert system. Press it to instantly notify your supervisors and admin team that you need support.' },
      { q: 'Who receives MAYDAY alerts?', a: 'MAYDAY alerts go to all configured Mayday Contacts for your agency — typically BCBAs, program directors, and on-call supervisors.' },
      { q: 'What urgency levels are available?', a: 'Three levels: Urgent (immediate physical safety concern), High (escalating situation), and Standard (non-emergency support request).' },
      { q: 'Can I cancel a MAYDAY alert?', a: 'Yes. After sending, you can resolve or cancel the alert. This updates all recipients immediately.' },
      { q: 'How do I know if a Mayday alert was sent?', a: 'After sending, the system shows a confirmation and recipient status. If not, check your Mayday settings.' },
    ],
  },
  {
    title: 'IEP Tools',
    icon: FileText,
    items: [
      { q: 'What is the IEP Reader?', a: 'The IEP Reader lets you upload IEP documents (PDF). Beacon uses AI to extract goals, accommodations, services, and progress data.' },
      { q: 'What is the IEP Writer?', a: "The IEP Writer helps generate IEP goals, FBA narratives, and BIP documents using AI, pulling from the student's collected data." },
      { q: 'Do I need to be a BCBA to use the IEP tools?', a: 'No! Teachers can upload IEPs and view extracted information. Approving goals and generating clinical documents is typically reserved for BCBAs.' },
    ],
  },
  {
    title: 'Classroom Management',
    icon: Settings,
    items: [
      { q: 'How do I set up a new classroom?', a: 'Go to the Classroom Manager. Tap Create Classroom and enter a name, school, and grade band. Then add students and assign staff.' },
      { q: 'Can I be assigned to multiple classrooms?', a: 'Yes! Use the classroom selector to switch between them. Your data and settings are maintained separately.' },
      { q: 'How do I add students to my classroom?', a: 'In the Classroom Manager, select your classroom and tap Add Students. Choose from the students assigned to your agency.' },
      { q: 'What staff roles are available?', a: 'Teacher, Behavior Interventionist (BI), Aide, BCBA, SPED, SLP, OT, and Other. Each shows as a role badge.' },
      { q: 'How do Guest Access Codes work?', a: 'Guest Access Codes are temporary, time-limited codes for substitute teachers. Generate one from the Classroom Manager.' },
      { q: 'How do I assign staff to a classroom?', a: 'Go to the Classroom Manager, select a classroom, and add staff members under the assignment section.' },
    ],
  },
  {
    title: "Who's Here & Staff",
    icon: Eye,
    items: [
      { q: "Why can't I see other staff in Who's Here?", a: "Who's Here only shows active staff in your agency or classroom. If someone is missing, they may not be logged in or assigned to your group." },
      { q: 'How do I reset a student\'s token board?', a: 'Open the student\'s quick actions and select Reset Token Board.' },
      { q: 'Can students see other students\' data?', a: 'No. Student views are isolated and privacy-protected.' },
    ],
  },
  {
    title: 'Reports & Data',
    icon: BarChart3,
    items: [
      { q: 'What reports are available?', a: 'Weekly Data Summaries, Parent Reports, and detailed data exports. All pull from your real-time data.' },
      { q: 'How do Weekly Trend Charts work?', a: 'Trend Charts automatically graph your collected data over time — frequency trends, duration averages, engagement percentages, and ABC patterns.' },
      { q: 'Can I export data?', a: 'Data can be viewed in-app through summaries and trend charts. Your BCBA or administrator can access full data through the admin dashboard.' },
    ],
  },
  {
    title: 'Account & Settings',
    icon: Settings,
    items: [
      { q: 'How do I change my notification settings?', a: "Go to Settings → Notifications. Toggle engagement prompts, data log reminders, escalation alerts, and more. Set quiet hours for off-school times." },
      { q: 'How do I reset my password?', a: "From the login page, tap Forgot Password. Enter your email and you'll receive a reset link." },
      { q: 'Can I switch between agencies or workspaces?', a: "If you belong to multiple agencies, you'll see a Workspace Selector when you log in." },
      { q: 'What data can my BCBA see?', a: 'Your BCBA can see all collected data — frequency counts, duration logs, ABC entries, engagement checks, and skill probes. They cannot see your personal settings.' },
    ],
  },
];

/* ═══════════════════════════════════════════════════════════ */
/*  MOST USED / TROUBLESHOOTING / QUICK FIXES                */
/* ═══════════════════════════════════════════════════════════ */

const mostUsed = [
  { label: 'Send Mayday', icon: AlertTriangle, answer: 'Classroom View → Red MAYDAY button → Select urgency → Send. All configured contacts are notified instantly.' },
  { label: 'Add Points', icon: Star, answer: 'Tap the + button on any student card → Enter point amount → Done. Points appear instantly on the Game Board.' },
  { label: 'Message Staff', icon: MessageCircle, answer: 'Go to Threads → Select or create a thread → Type message → Send. Use @mentions for specific staff.' },
  { label: 'Message Parent', icon: Heart, answer: 'Student Detail → Parent Snapshot → Copy link → Share via text or email. No parent login required.' },
  { label: 'Use Game Board', icon: Gamepad2, answer: 'Board Settings → Copy board URL → Open on smartboard browser. Auto-updates in real time.' },
];

const troubleshooting = [
  { problem: 'Mayday not sending', fix: 'Check that Mayday contacts are configured in your agency settings. Ensure at least one contact has active notification channels (email/in-app).' },
  { problem: 'Game Board not loading', fix: 'Verify students are assigned to the classroom group. Check that the board slug is set in Board Settings. Try refreshing the page.' },
  { problem: 'Threads not updating', fix: 'Refresh the page. Check your internet connection. Confirm you are viewing the correct classroom or agency thread.' },
  { problem: 'Students not showing', fix: 'Ensure students are assigned to your classroom in the Classroom Manager. If you recently switched workspaces, select the correct one.' },
  { problem: 'Points not appearing', fix: 'Check if the student has a reinforcement profile assigned. Verify point rules are active. Try a manual point award to test.' },
  { problem: 'Rewards not showing', fix: 'Ensure rewards are marked as active in the Reward Store settings. Check that the student has enough points to see available rewards.' },
];

const quickFixes = [
  { issue: 'Access Not Configured', fix: 'Clear session storage → Refresh → Or click the Retry button on the error screen.' },
  { issue: 'Blank classroom', fix: 'Switch to the correct workspace using the dropdown in the header.' },
  { issue: 'Engagement prompts not appearing', fix: 'Check notification settings. Ensure prompts are enabled and intervals are configured.' },
  { issue: 'Can\'t see staff presence', fix: 'Staff must be logged in and assigned to your classroom group.' },
  { issue: 'Data not saving', fix: 'Check internet connection. Data syncs automatically when reconnected.' },
];

/* ═══════════════════════════════════════════════════════════ */
/*  TUTORIALS                                                  */
/* ═══════════════════════════════════════════════════════════ */

interface TutorialStep { step: number; title: string; description: string; icon: React.ElementType }
interface TutorialSection { title: string; description: string; steps: TutorialStep[] }

const tutorials: TutorialSection[] = [
  {
    title: 'Your First Day with Beacon',
    description: 'A step-by-step guide to get through your first school day using Beacon.',
    steps: [
      { step: 1, title: 'Sign in & check your Classroom', description: "Log in and navigate to the Classroom View. You'll see your assigned students, their attendance from yesterday, and any staff notes.", icon: Users },
      { step: 2, title: 'Take morning attendance', description: "Tap each student's attendance indicator to mark them Present, Absent, or Tardy. This takes about 30 seconds for a full class.", icon: Clock },
      { step: 3, title: 'Start data collection', description: 'Open Quick Add for your first student. Tap the behavior buttons as you observe them during morning routine.', icon: BarChart3 },
      { step: 4, title: 'Award Beacon Points', description: 'When students follow routines, award points manually with one tap or let auto-rules handle it.', icon: Star },
      { step: 5, title: 'Check engagement prompts', description: "If your BCBA has set up interval prompts, they'll pop up during instruction. Just tap On Task or Off Task.", icon: Target },
      { step: 6, title: 'Send a Parent Snapshot', description: 'At the end of the day, generate a Parent Snapshot link for any student. Share via text — families love the positive highlights!', icon: MessageCircle },
    ],
  },
  {
    title: 'Setting Up Your Classroom',
    description: 'How to configure your classroom for the first time.',
    steps: [
      { step: 1, title: 'Create your classroom group', description: 'Go to Classroom Manager from the More menu. Tap Create Classroom and enter a name, school name, and grade band.', icon: Users },
      { step: 2, title: 'Add students', description: 'Select your classroom and tap Add Students. Pick students from your agency roster.', icon: BookOpen },
      { step: 3, title: 'Assign staff', description: 'Add yourself and any co-teachers, BIs, or aides. Select the correct role for each person.', icon: Users },
      { step: 4, title: 'Configure the Game Board', description: 'Go to Board Settings and set your classroom slug, mission text, word of the week, and class goal.', icon: Gamepad2 },
      { step: 5, title: 'Set up rewards', description: 'Go to the Rewards page and add at least 3-5 rewards with different point costs.', icon: Gift },
    ],
  },
  {
    title: 'Running an Effective Data Day',
    description: 'Best practices for consistent, high-quality data collection.',
    steps: [
      { step: 1, title: 'Check your targets', description: 'Review which behaviors and skills you are tracking today.', icon: Target },
      { step: 2, title: 'Use Quick Add for frequency', description: 'For behaviors that happen frequently, keep Quick Add open. One tap per occurrence.', icon: BarChart3 },
      { step: 3, title: 'Time durations when needed', description: 'For behaviors with duration, use the timer. Tap start when it begins, stop when it ends.', icon: Clock },
      { step: 4, title: 'Log ABC for significant incidents', description: 'When a notable behavior occurs, log the full ABC for functional analysis context.', icon: FileText },
      { step: 5, title: 'Respond to engagement prompts', description: 'When prompted, take a quick scan and tap On Task or Off Task. Consistency matters.', icon: Target },
      { step: 6, title: 'End-of-day review', description: 'Check the data summary to make sure nothing was missed. Add notes while the day is fresh.', icon: BookOpen },
    ],
  },
  {
    title: 'Send Your First Mayday',
    description: 'Quickly request help from staff.',
    steps: [
      { step: 1, title: 'Find the Mayday button', description: 'Look for the red MAYDAY button at the bottom of the Classroom View. It is always accessible.', icon: AlertTriangle },
      { step: 2, title: 'Select urgency level', description: 'Choose Urgent, High, or Standard based on the situation severity.', icon: Megaphone },
      { step: 3, title: 'Add context and send', description: 'Add an optional note describing the situation, then tap Send. All contacts are notified instantly.', icon: Send },
    ],
  },
  {
    title: 'Add Points to a Student',
    description: 'Reinforce positive behavior with one tap.',
    steps: [
      { step: 1, title: 'Select the student', description: 'Tap the student card in the Classroom View.', icon: Users },
      { step: 2, title: 'Choose the behavior', description: 'Select the positive behavior or use the + button for manual points.', icon: Star },
      { step: 3, title: 'Confirm points', description: 'Points are added instantly and visible on the Game Board.', icon: CheckCircle2 },
    ],
  },
  {
    title: 'Create a Classroom',
    description: 'Set up your classroom environment.',
    steps: [
      { step: 1, title: 'Open Classroom Manager', description: 'Navigate to More → Classroom Manager from the top navigation.', icon: LayoutDashboard },
      { step: 2, title: 'Create the classroom', description: 'Tap Create Classroom and enter the name, school, and grade band.', icon: Users },
      { step: 3, title: 'Assign staff and students', description: 'Add team members and students from your agency roster.', icon: UserPlus },
    ],
  },
  {
    title: "Use Who's Here",
    description: 'See who is available to help.',
    steps: [
      { step: 1, title: 'Open the Classroom View', description: "The Who's Here panel shows a count of present students.", icon: Eye },
      { step: 2, title: 'View staff presence', description: 'See which staff are in-room, available, or elsewhere.', icon: Users },
      { step: 3, title: 'Tap to message or request help', description: 'Quickly coordinate with available staff members.', icon: MessageCircle },
    ],
  },
  {
    title: 'Send a Staff Message',
    description: 'Communicate quickly with your team.',
    steps: [
      { step: 1, title: 'Open Threads', description: 'Navigate to the Threads tab in the main navigation.', icon: MessageCircle },
      { step: 2, title: 'Select or create a thread', description: 'Choose an existing thread or tap Create New.', icon: Send },
      { step: 3, title: 'Send your message', description: 'Type your message and press Send. Delivered instantly to all members.', icon: CheckCircle2 },
    ],
  },
  {
    title: 'Use the Reward Store',
    description: 'Motivate students with redeemable rewards.',
    steps: [
      { step: 1, title: 'Open Rewards', description: 'Navigate to the Rewards tab in the main navigation.', icon: Gift },
      { step: 2, title: 'Select a reward', description: 'Browse available items and select one to redeem for a student.', icon: Star },
      { step: 3, title: 'Confirm redemption', description: 'Points are deducted and the reward is recorded.', icon: CheckCircle2 },
    ],
  },
  {
    title: 'Share a Parent Link',
    description: 'Give parents secure access to their child\'s progress.',
    steps: [
      { step: 1, title: 'Open student detail', description: 'Tap a student card in the Classroom View to open their detail page.', icon: Users },
      { step: 2, title: 'Generate parent link', description: 'Tap Parent Snapshot or Quick Actions → Share Link.', icon: Eye },
      { step: 3, title: 'Share with parent', description: 'Copy and send the link via text, email, or messaging app.', icon: Send },
    ],
  },
];

/* ═══════════════════════════════════════════════════════════ */
/*  FEATURES DATA                                              */
/* ═══════════════════════════════════════════════════════════ */

const features = [
  {
    category: 'Classroom Management',
    icon: LayoutDashboard,
    items: ['Live classroom dashboard', 'Student cards with behavior tracking', 'Token boards per student', 'Group and individual reinforcement systems', 'Visual classroom engagement tools'],
  },
  {
    category: 'Data Collection & ABA Tools',
    icon: BarChart3,
    items: ['Real-time behavior tracking', 'Custom behavior targets', 'Probe and engagement data', 'Session-based tracking', 'Auto summaries and insights'],
  },
  {
    category: 'Beacon Points & Rewards',
    icon: Star,
    items: ['Flexible point system', 'Student-specific reinforcement', 'Reward store with redemption tracking', 'Positive reinforcement automation', 'Token-to-reward conversion'],
  },
  {
    category: 'Game Board',
    icon: Gamepad2,
    items: ['Classroom race system', 'Checkpoint-based progress', 'Live leaderboard', 'Student motivation visualization', 'Projector-friendly display'],
  },
  {
    category: 'Communication (Threads)',
    icon: MessageCircle,
    items: ['Slack-style messaging', 'Agency-wide thread', 'Classroom threads (auto-created)', 'Direct messages and group chats', '@mentions and notifications'],
  },
  {
    category: "Who's Here (Live Staff)",
    icon: Eye,
    items: ['Real-time staff availability', 'Room-based presence tracking', 'Quick help coordination', 'Mayday integration', 'Tap-to-message staff'],
  },
  {
    category: 'Safety & Mayday',
    icon: Shield,
    items: ['Instant emergency alerts', 'Admin-managed contact list', 'Multi-recipient notifications', 'Classroom-based escalation', 'Live response tracking'],
  },
  {
    category: 'Parent Engagement',
    icon: Heart,
    items: ['Parent portal access', 'Student progress visibility', 'Rewards tracking', 'Classroom updates feed', 'Secure communication'],
  },
  {
    category: 'External Access',
    icon: Smartphone,
    items: ['Parent links', 'Student links', 'Secure token-based access', 'No login required', 'Controlled visibility'],
  },
  {
    category: 'Staff Coordination',
    icon: UserCog,
    items: ['Room assignments', 'Staff movement tracking', 'Support coordination', 'Admin controls', 'Real-time updates'],
  },
];

/* ═══════════════════════════════════════════════════════════ */
/*  ROLE-BASED TRAINING TRACKS                                */
/* ═══════════════════════════════════════════════════════════ */

interface TrackStep {
  title: string;
  action: string;
  detail: string;
  icon: React.ElementType;
  tip?: string;
}

interface TrackModule {
  title: string;
  description: string;
  icon: React.ElementType;
  steps: TrackStep[];
}

interface RoleTrack {
  role: string;
  label: string;
  emoji: string;
  color: string;
  icon: React.ElementType;
  description: string;
  modules: TrackModule[];
}

const roleTracks: RoleTrack[] = [
  {
    role: 'teacher',
    label: 'Teacher',
    emoji: '\uD83D\uDC69\u200D\uD83C\uDFEB',
    color: 'bg-emerald-500',
    icon: GraduationCap,
    description: 'Everything you need to run a Beacon-powered classroom from day one.',
    modules: [
      {
        title: 'First Day Setup', description: 'Get your classroom ready in under 10 minutes.', icon: Smartphone,
        steps: [
          { title: 'Install Beacon on your device', action: 'Open Beacon in Safari/Chrome → Tap Share → Add to Home Screen', detail: 'This gives you a native-app experience with offline support and push notifications.', icon: Smartphone, tip: 'Pin it right next to your most-used apps so it becomes part of your routine.' },
          { title: 'Sign in with your credentials', action: 'Enter the email and password your admin provided', detail: 'If you received an invite code instead, go to the Join page and enter the code first.', icon: LogIn },
          { title: 'Check your Classroom View', action: 'Tap Classroom in the bottom nav', detail: "You should see your students listed with yesterday's attendance. If the list is empty, contact your admin.", icon: Users, tip: 'This screen is your home base — you will start here every morning.' },
          { title: 'Take your first attendance', action: "Tap each student's colored dot → Select Present, Absent, or Tardy", detail: 'Changes save instantly and are visible to your whole team.', icon: CheckCircle2 },
          { title: 'Open the Game Board on your smartboard', action: 'Navigate to Board Settings → Copy the board URL → Open on your display', detail: 'Students will see their avatars, points, and class goal in real time.', icon: Gamepad2, tip: 'Bookmark the board URL on your smartboard browser for one-click access each morning.' },
        ],
      },
      {
        title: 'Running a Classroom', description: 'Your daily Beacon workflow from bell to bell.', icon: Users,
        steps: [
          { title: 'Morning: Take attendance', action: 'Classroom View → Tap attendance dots for each student', detail: 'Mark Present, Absent, Tardy, or Early Dismissal.', icon: CheckCircle2 },
          { title: 'Update student presence throughout the day', action: 'Tap a student → Change location (Classroom, Pull-out, Bathroom, etc.)', detail: 'Presence tracking lets your team know where every student is at all times.', icon: Eye },
          { title: 'Log behaviors as they happen', action: 'Quick Add → Select student → Tap behavior button', detail: 'Each tap records one occurrence with an automatic timestamp.', icon: BarChart3 },
          { title: 'Respond to engagement prompts', action: 'When the prompt pops up → Tap On Task or Off Task', detail: 'Takes 2 seconds. If you are mid-instruction, tap Snooze.', icon: Target, tip: 'Consistency over perfection. Even partial engagement data is valuable for your BCBA.' },
          { title: 'End-of-day: Send parent snapshots', action: 'Student Detail → Parent Snapshot → Share link', detail: 'Families see a positive summary of the day.', icon: Send },
        ],
      },
      {
        title: 'Using Points & Token Board', description: 'Maximize your token economy.', icon: Star,
        steps: [
          { title: 'Award points for positive behavior', action: 'Tap the + button on any student → Enter points → Done', detail: 'Points appear instantly on the Game Board.', icon: Star },
          { title: 'Use Bulk Award for class-wide recognition', action: 'Classroom View → Bulk Award → Select students → Enter points', detail: 'Perfect for transitions and group activities.', icon: Users },
          { title: 'Monitor token boards', action: 'Check the Game Board or individual student cards', detail: 'Tokens fill up as students approach their goal.', icon: Gamepad2, tip: 'Narrate the progress aloud: "Jamie only needs 5 more points!"' },
          { title: 'Let students redeem rewards', action: 'Students browse the Reward Store → Request redemption → You approve', detail: 'Builds self-management skills.', icon: Gift },
        ],
      },
      {
        title: 'Sending Mayday', description: 'Get immediate support when you need it.', icon: AlertTriangle,
        steps: [
          { title: 'Locate the Mayday button', action: 'Bottom of the Classroom View → Red MAYDAY button', detail: 'Always accessible from your main screen.', icon: AlertTriangle },
          { title: 'Select urgency and send', action: 'Choose Urgent / High / Standard → Add optional note → Send', detail: 'All configured contacts receive the alert immediately.', icon: Megaphone, tip: "Don't hesitate to use it. That's exactly what it's for." },
          { title: 'Wait for acknowledgment', action: 'The alert status updates in real time as contacts respond', detail: 'You can resolve or cancel the alert once handled.', icon: CheckCircle2 },
        ],
      },
      {
        title: 'Messaging Staff', description: 'Coordinate without leaving the app.', icon: MessageCircle,
        steps: [
          { title: 'Start or join a Thread', action: 'Threads tab → Create New or tap existing thread', detail: 'Use public threads for team-wide updates, private for sensitive topics.', icon: MessageCircle },
          { title: 'Send a message', action: 'Type your message → Tap Send', detail: 'Delivered instantly. Supports @mentions and images.', icon: Send },
          { title: 'Use Inbox for formal messages', action: 'Inbox tab → Compose → Add recipients and attachments', detail: 'Inbox messages can be pinned to specific students.', icon: FileText, tip: 'Threads for quick coordination, Inbox for things that need to be found later.' },
        ],
      },
      {
        title: 'Messaging Parents', description: 'Keep families informed with zero effort.', icon: Heart,
        steps: [
          { title: 'Generate a Parent Snapshot', action: 'Student Detail → Tap Parent Snapshot', detail: 'Creates a secure, time-limited link with daily highlights.', icon: Eye },
          { title: 'Share the link', action: 'Copy link → Send via text, email, or school messaging', detail: 'Parents open it in any browser — no account needed.', icon: Send },
          { title: 'Review what parents see', action: 'Tap Preview to see the snapshot before sharing', detail: 'Focuses on positive highlights and progress.', icon: Heart, tip: 'Sending a snapshot after a great day builds trust and parent engagement.' },
        ],
      },
    ],
  },
  {
    role: 'admin',
    label: 'Admin / BCBA',
    emoji: '\uD83D\uDC69\u200D\uD83D\uDCBC',
    color: 'bg-blue-500',
    icon: UserCog,
    description: 'Set up and manage Beacon for your team.',
    modules: [
      {
        title: 'Creating Classrooms', description: 'Set up classroom groups for your staff.', icon: LayoutDashboard,
        steps: [
          { title: 'Open Classroom Manager', action: 'More menu → Classroom Manager', detail: 'Create, edit, and manage all classroom groups.', icon: LayoutDashboard },
          { title: 'Create a new classroom', action: 'Tap Create Classroom → Enter name, school, grade band', detail: 'Use descriptive names like "Room 12 — Ms. Rivera".', icon: Users },
          { title: 'Set the board slug', action: 'Edit classroom → Set a URL-friendly slug', detail: 'Creates a shareable URL for the Game Board.', icon: Gamepad2, tip: 'Keep slugs short and memorable.' },
        ],
      },
      {
        title: 'Assigning Staff', description: 'Add teachers, BIs, aides to classrooms.', icon: UserPlus,
        steps: [
          { title: 'Select the classroom', action: 'Classroom Manager → Tap the classroom', detail: 'View current roster and staff assignments.', icon: Users },
          { title: 'Add staff members', action: 'Tap Add Staff → Search by name → Select role', detail: 'Roles: Teacher, BI, Aide, BCBA, SPED, SLP, OT, Other.', icon: UserPlus },
          { title: 'Verify role badges', action: 'Check Classroom View for correct badge display', detail: 'Each staff member shows their role badge.', icon: CheckCircle2, tip: 'Staff can be in multiple classrooms with different roles.' },
        ],
      },
      {
        title: "Managing Who's Here", description: 'Real-time visibility into presence.', icon: Eye,
        steps: [
          { title: "Open Who's Here panel", action: "Classroom View → Who's Here section", detail: 'Live count of present vs. absent students.', icon: Eye },
          { title: 'View Staff Presence', action: 'Scroll to Staff Presence panel', detail: 'See which staff are in-room, on break, or elsewhere.', icon: Users },
          { title: 'Update a student location', action: 'Tap student → Change presence', detail: 'Entire team sees updates instantly.', icon: Target, tip: 'During drills, verify all locations from this panel.' },
        ],
      },
      {
        title: 'Configuring Mayday Contacts', description: 'Ensure alerts reach the right people.', icon: Shield,
        steps: [
          { title: 'Open Mayday Contacts Manager', action: 'Settings or Admin Dashboard → Mayday Contacts', detail: 'Define who receives MAYDAY alerts.', icon: Shield },
          { title: 'Add a contact', action: 'Tap Add Contact → Enter name, email, phone → Set channels', detail: 'Choose email, SMS, in-app, or all three.', icon: UserPlus },
          { title: 'Set availability and overrides', action: 'Configure opt-out days, admin override, active status', detail: 'Deactivate during vacation without removing.', icon: Settings, tip: 'Always have at least 2 active contacts for safety.' },
        ],
      },
      {
        title: 'Viewing Reports', description: 'Access data summaries and trends.', icon: TrendingUp,
        steps: [
          { title: 'Open Weekly Data Summary', action: 'Data Summary page → Select student and date range', detail: 'Auto-generated trend charts for frequency, duration, engagement.', icon: BarChart3 },
          { title: 'Generate Parent Reports', action: 'Parent Reports page → Select student → Generate', detail: 'Family-friendly summaries with highlights.', icon: FileText },
          { title: 'Review IEP data linkage', action: 'IEP Reader → View extracted goals alongside collected data', detail: 'Match IEP goals to real behavior data.', icon: BookOpen, tip: 'Use trend data in IEP meetings for concrete evidence.' },
        ],
      },
    ],
  },
  {
    role: 'parent',
    label: 'Parent / Family',
    emoji: '\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67',
    color: 'bg-purple-500',
    icon: Heart,
    description: 'Stay connected to your child\'s classroom — no app download needed.',
    modules: [
      {
        title: 'Viewing Child Progress', description: "See your child's daily highlights.", icon: Eye,
        steps: [
          { title: 'Open the snapshot link', action: 'Tap the link your teacher shared via text or email', detail: 'Opens in any browser — no login required.', icon: Smartphone },
          { title: 'Review daily highlights', action: 'Scroll through the summary card', detail: 'See points earned, positive behaviors, and teacher notes.', icon: Star },
          { title: 'Check the points balance', action: 'View current point total and recent transactions', detail: 'Points represent positive classroom recognition.', icon: TrendingUp, tip: 'Ask your child about their points! It reinforces positive behavior at home.' },
        ],
      },
      {
        title: 'Understanding Rewards', description: 'How Beacon Points rewards work.', icon: Gift,
        steps: [
          { title: 'Points = classroom currency', action: 'Earned for following rules, staying on task, positive interactions', detail: 'Teachers award points throughout the day.', icon: Star },
          { title: 'Rewards are earned, not given', action: 'Students choose from the Reward Store when they have enough points', detail: 'Includes free time, activities, small tangible items.', icon: Gift },
          { title: 'Token boards show progress', action: 'On the classroom Game Board, your child has an avatar that advances', detail: "A fun, visual motivator for the whole class.", icon: Gamepad2, tip: 'Celebrate milestones together at home!' },
        ],
      },
      {
        title: 'Messaging Teacher', description: 'How school-home communication works.', icon: MessageCircle,
        steps: [
          { title: 'Parent Snapshots are read-only', action: 'Snapshots share positive highlights — one-way summaries', detail: 'Focused on what went well during the day.', icon: Eye },
          { title: 'For questions, contact teacher directly', action: 'Use your existing school communication channel', detail: 'Beacon focuses on data and classroom management.', icon: MessageCircle },
          { title: 'Ask about Behavior Decoded', action: 'The companion parent app provides two-way features', detail: 'Ask your teacher if your school uses it.', icon: Smartphone, tip: 'Regular communication with your child\'s teacher has the biggest impact.' },
        ],
      },
      {
        title: 'Reading Updates', description: 'Understanding shared information.', icon: FileText,
        steps: [
          { title: 'What you see in a snapshot', action: 'Points earned, positive behavior highlights, daily summary', detail: 'Generated by the teacher at end of day.', icon: Eye },
          { title: 'Understanding behavior data', action: 'Trend charts show progress over weeks', detail: 'Upward trends in positive behaviors show growth.', icon: TrendingUp },
          { title: 'IEP progress updates', action: 'BCBAs may share Beacon data visuals in IEP meetings', detail: 'Charts from real daily classroom data.', icon: BookOpen, tip: 'Keep snapshots — great conversation starters at parent-teacher conferences!' },
        ],
      },
    ],
  },
];

/* ═══════════════════════════════════════════════════════════ */
/*  COMPONENT                                                 */
/* ═══════════════════════════════════════════════════════════ */

type TabKey = 'faq' | 'tutorials' | 'tracks' | 'features';

const FAQTutorial = () => {
  const navigate = useNavigate();
  const [search, setSearch] = useState('');
  const [activeTab, setActiveTab] = useState<TabKey>('faq');
  const [activeTrack, setActiveTrack] = useState<string>('teacher');
  const [completedSteps, setCompletedSteps] = useState<Set<string>>(new Set());
  const [expandedModules, setExpandedModules] = useState<Set<string>>(new Set());

  const toggleStep = (key: string) => {
    setCompletedSteps((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  const toggleModule = (key: string) => {
    setExpandedModules((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  const filteredSections = faqSections
    .map((section) => ({
      ...section,
      items: section.items.filter(
        (item) =>
          item.q.toLowerCase().includes(search.toLowerCase()) ||
          item.a.toLowerCase().includes(search.toLowerCase()),
      ),
    }))
    .filter((section) => section.items.length > 0);

  const totalQuestions = faqSections.reduce((sum, s) => sum + s.items.length, 0);
  const currentTrack = roleTracks.find((t) => t.role === activeTrack) || roleTracks[0];
  const totalTrackSteps = currentTrack.modules.reduce((sum, m) => sum + m.steps.length, 0);
  const completedTrackSteps = currentTrack.modules.reduce(
    (sum, m, mi) =>
      sum + m.steps.filter((_, si) => completedSteps.has(`${currentTrack.role}-${mi}-${si}`)).length,
    0,
  );
  const trackProgress = totalTrackSteps > 0 ? Math.round((completedTrackSteps / totalTrackSteps) * 100) : 0;

  const tabs: { key: TabKey; label: string; icon: React.ElementType }[] = [
    { key: 'faq', label: 'FAQ', icon: HelpCircle },
    { key: 'tutorials', label: 'Tutorials', icon: BookOpen },
    { key: 'tracks', label: 'Training', icon: GraduationCap },
    { key: 'features', label: 'Features', icon: Zap },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-background via-background to-muted/30">
      {/* Top bar */}
      <div className="sticky top-0 z-50 bg-card/80 backdrop-blur-md border-b border-border/50">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="icon" onClick={() => navigate('/tour')} className="shrink-0">
              <ArrowLeft className="h-4 w-4" />
            </Button>
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <Zap className="h-4 w-4 text-primary-foreground" />
            </div>
            <span className="font-bold text-foreground text-lg">Beacon</span>
            <Badge variant="secondary" className="text-[10px] ml-1">Help Center</Badge>
          </div>
          <Button size="sm" onClick={() => navigate('/login')} className="gap-1.5">
            <LogIn className="h-4 w-4" />
            <span className="hidden sm:inline">Sign In</span>
          </Button>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8 space-y-8">
        {/* Header */}
        <div className="text-center space-y-3">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary text-xs font-medium">
            <HelpCircle className="h-3.5 w-3.5" />
            {totalQuestions} questions · {tutorials.length} tutorials · 3 training tracks
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-foreground">
            Help Center & Training
          </h1>
          <p className="text-muted-foreground text-base max-w-xl mx-auto">
            Everything you need — from quick answers to guided, step-by-step training for your role.
          </p>
        </div>

        {/* Tab toggle */}
        <div className="flex items-center justify-center gap-1 p-1 bg-muted rounded-xl w-fit mx-auto overflow-x-auto">
          {tabs.map((tab) => {
            const TIcon = tab.icon;
            return (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className={`px-3 sm:px-5 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-1.5 whitespace-nowrap ${
                  activeTab === tab.key
                    ? 'bg-card text-foreground shadow-sm'
                    : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                <TIcon className="h-4 w-4" />
                <span className="hidden sm:inline">{tab.label}</span>
                <span className="sm:hidden">{tab.label.split(' ')[0]}</span>
              </button>
            );
          })}
        </div>

        {/* ─── FAQ TAB ─── */}
        {activeTab === 'faq' && (
          <>
            <div className="relative max-w-md mx-auto">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input placeholder="Search questions…" value={search} onChange={(e) => setSearch(e.target.value)} className="pl-10" />
            </div>

            {/* Most Used Actions */}
            {!search && (
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <Flame className="h-4 w-4 text-orange-500" />
                  <h2 className="text-lg font-semibold text-foreground">Most Used</h2>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {mostUsed.map((item) => {
                    const IIcon = item.icon;
                    return (
                      <Card key={item.label} className="border-border/50">
                        <CardContent className="p-4">
                          <div className="flex items-start gap-3">
                            <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                              <IIcon className="h-4 w-4 text-primary" />
                            </div>
                            <div>
                              <h3 className="text-sm font-semibold text-foreground">{item.label}</h3>
                              <p className="text-xs text-muted-foreground mt-1 leading-relaxed">{item.answer}</p>
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Troubleshooting */}
            {!search && (
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <Wrench className="h-4 w-4 text-amber-500" />
                  <h2 className="text-lg font-semibold text-foreground">Troubleshooting</h2>
                </div>
                <Card className="border-border/50">
                  <CardContent className="p-0">
                    <Accordion type="multiple" className="w-full">
                      {troubleshooting.map((item, i) => (
                        <AccordionItem key={i} value={`trouble-${i}`} className="border-border/30 last:border-b-0">
                          <AccordionTrigger className="px-4 py-3 text-sm font-medium text-foreground hover:no-underline text-left">
                            <span className="flex items-center gap-2">
                              <AlertTriangle className="h-3.5 w-3.5 text-amber-500 shrink-0" />
                              {item.problem}
                            </span>
                          </AccordionTrigger>
                          <AccordionContent className="px-4 pb-4 text-sm text-muted-foreground leading-relaxed">
                            {item.fix}
                          </AccordionContent>
                        </AccordionItem>
                      ))}
                    </Accordion>
                  </CardContent>
                </Card>
              </div>
            )}

            {/* Quick Fixes */}
            {!search && (
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <Lightbulb className="h-4 w-4 text-yellow-500" />
                  <h2 className="text-lg font-semibold text-foreground">Quick Fixes</h2>
                </div>
                <div className="space-y-2">
                  {quickFixes.map((item, i) => (
                    <div key={i} className="flex items-start gap-3 px-4 py-3 rounded-xl bg-muted/50 border border-border/30">
                      <ChevronRight className="h-4 w-4 text-primary mt-0.5 shrink-0" />
                      <div>
                        <span className="text-sm font-medium text-foreground">{item.issue}</span>
                        <span className="text-sm text-muted-foreground"> → {item.fix}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Category chips */}
            {!search && (
              <div className="flex flex-wrap items-center justify-center gap-2">
                {faqSections.map((section) => {
                  const SIcon = section.icon;
                  return (
                    <a key={section.title} href={`#faq-${section.title.toLowerCase().replace(/\s+/g, '-')}`} className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium bg-muted text-muted-foreground hover:bg-muted/80 transition-all">
                      <SIcon className="h-3.5 w-3.5" />
                      {section.title}
                    </a>
                  );
                })}
              </div>
            )}

            <div className="space-y-6">
              {filteredSections.map((section) => {
                const SIcon = section.icon;
                return (
                  <div key={section.title} id={`faq-${section.title.toLowerCase().replace(/\s+/g, '-')}`} className="scroll-mt-20">
                    <div className="flex items-center gap-2 mb-3">
                      <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                        <SIcon className="h-4 w-4 text-primary" />
                      </div>
                      <h2 className="text-lg font-semibold text-foreground">{section.title}</h2>
                      <Badge variant="outline" className="text-[10px] ml-auto">
                        {section.items.length}
                      </Badge>
                    </div>
                    <Card className="border-border/50">
                      <CardContent className="p-0">
                        <Accordion type="multiple" className="w-full">
                          {section.items.map((item, i) => (
                            <AccordionItem key={i} value={`${section.title}-${i}`} className="border-border/30 last:border-b-0">
                              <AccordionTrigger className="px-4 py-3 text-sm font-medium text-foreground hover:no-underline text-left">
                                {item.q}
                              </AccordionTrigger>
                              <AccordionContent className="px-4 pb-4 text-sm text-muted-foreground leading-relaxed">
                                {item.a}
                              </AccordionContent>
                            </AccordionItem>
                          ))}
                        </Accordion>
                      </CardContent>
                    </Card>
                  </div>
                );
              })}
              {filteredSections.length === 0 && (
                <div className="text-center py-12">
                  <HelpCircle className="h-10 w-10 text-muted-foreground/30 mx-auto mb-3" />
                  <p className="text-muted-foreground">No questions match &quot;{search}&quot;</p>
                  <Button variant="link" size="sm" onClick={() => setSearch('')} className="mt-1">Clear search</Button>
                </div>
              )}
            </div>
          </>
        )}

        {/* ─── TUTORIALS TAB ─── */}
        {activeTab === 'tutorials' && (
          <div className="space-y-8">
            {tutorials.map((tutorial, tIdx) => (
              <Card key={tIdx} className="border-border/50 overflow-hidden">
                <div className="p-6 border-b border-border/30 bg-muted/30">
                  <div className="flex items-start gap-3">
                    <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0 mt-0.5">
                      <BookOpen className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-foreground">{tutorial.title}</h3>
                      <p className="text-sm text-muted-foreground mt-0.5">{tutorial.description}</p>
                    </div>
                  </div>
                </div>
                <CardContent className="p-0">
                  {tutorial.steps.map((step, sIdx) => {
                    const StepIcon = step.icon;
                    return (
                      <div key={sIdx} className="flex items-start gap-4 px-6 py-4 border-b border-border/20 last:border-b-0">
                        <div className="shrink-0 flex flex-col items-center gap-1">
                          <div className="w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-sm font-bold">
                            {step.step}
                          </div>
                          {sIdx < tutorial.steps.length - 1 && <div className="w-px h-full min-h-[16px] bg-border/40" />}
                        </div>
                        <div className="pt-1">
                          <div className="flex items-center gap-2 mb-1">
                            <StepIcon className="h-4 w-4 text-primary/70" />
                            <h4 className="text-sm font-semibold text-foreground">{step.title}</h4>
                          </div>
                          <p className="text-sm text-muted-foreground leading-relaxed">{step.description}</p>
                        </div>
                      </div>
                    );
                  })}
                </CardContent>
              </Card>
            ))}
          </div>
        )}

        {/* ─── FEATURES TAB ─── */}
        {activeTab === 'features' && (
          <div className="space-y-6">
            <div className="text-center space-y-2">
              <h2 className="text-2xl font-bold text-foreground">Everything Beacon Can Do</h2>
              <p className="text-sm text-muted-foreground max-w-lg mx-auto">
                A complete platform for classroom management, behavior tracking, and family engagement.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {features.map((section) => {
                const FIcon = section.icon;
                return (
                  <Card key={section.category} className="border-border/50">
                    <CardContent className="p-5">
                      <div className="flex items-center gap-2 mb-3">
                        <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                          <FIcon className="h-4 w-4 text-primary" />
                        </div>
                        <h3 className="text-sm font-semibold text-foreground">{section.category}</h3>
                      </div>
                      <ul className="space-y-1.5">
                        {section.items.map((item, j) => (
                          <li key={j} className="flex items-start gap-2 text-sm text-muted-foreground">
                            <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500 mt-0.5 shrink-0" />
                            {item}
                          </li>
                        ))}
                      </ul>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </div>
        )}

        {/* ─── TRAINING TRACKS TAB ─── */}
        {activeTab === 'tracks' && (
          <div className="space-y-6">
            {/* Role selector */}
            <div className="flex items-center justify-center gap-2 flex-wrap">
              {roleTracks.map((track) => {
                const TIcon = track.icon;
                return (
                  <button
                    key={track.role}
                    onClick={() => setActiveTrack(track.role)}
                    className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all border ${
                      activeTrack === track.role
                        ? 'bg-primary text-primary-foreground border-primary shadow-md'
                        : 'bg-card text-foreground border-border hover:border-primary/50'
                    }`}
                  >
                    <TIcon className="h-4 w-4" />
                    <span>{track.emoji} {track.label}</span>
                  </button>
                );
              })}
            </div>

            {/* Track header & progress */}
            <Card className="border-border/50 bg-gradient-to-r from-muted/50 to-muted/20">
              <CardContent className="p-6">
                <div className="flex items-start gap-4">
                  <div className={`w-12 h-12 rounded-2xl ${currentTrack.color} flex items-center justify-center shrink-0`}>
                    <currentTrack.icon className="h-6 w-6 text-white" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h2 className="text-xl font-bold text-foreground">
                      {currentTrack.emoji} {currentTrack.label} Track
                    </h2>
                    <p className="text-sm text-muted-foreground mt-1">{currentTrack.description}</p>
                    <div className="mt-3 flex items-center gap-3">
                      <Progress value={trackProgress} className="flex-1 h-2" />
                      <span className="text-xs font-medium text-muted-foreground whitespace-nowrap">
                        {completedTrackSteps}/{totalTrackSteps} steps
                      </span>
                    </div>
                    {completedTrackSteps === 0 && (
                      <Button
                        size="sm"
                        className="mt-3 gap-1.5"
                        onClick={() => {
                          const firstModKey = `${currentTrack.role}-mod-0`;
                          setExpandedModules((prev) => new Set(prev).add(firstModKey));
                        }}
                      >
                        <Play className="h-3.5 w-3.5" />
                        Start Learning
                      </Button>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Modules */}
            <div className="space-y-4">
              {currentTrack.modules.map((mod, mi) => {
                const modKey = `${currentTrack.role}-mod-${mi}`;
                const isOpen = expandedModules.has(modKey);
                const ModIcon = mod.icon;
                const modSteps = mod.steps.length;
                const modCompleted = mod.steps.filter((_, si) => completedSteps.has(`${currentTrack.role}-${mi}-${si}`)).length;
                const modProgress = modSteps > 0 ? Math.round((modCompleted / modSteps) * 100) : 0;

                return (
                  <Collapsible key={mi} open={isOpen} onOpenChange={() => toggleModule(modKey)}>
                    <Card className={`border-border/50 overflow-hidden transition-all ${modCompleted === modSteps && modSteps > 0 ? 'border-emerald-300/50 bg-emerald-50/30 dark:bg-emerald-950/10' : ''}`}>
                      <CollapsibleTrigger className="w-full text-left">
                        <div className="p-4 sm:p-5 flex items-center gap-3 hover:bg-muted/30 transition-colors">
                          <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
                            <ModIcon className="h-5 w-5 text-primary" />
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2">
                              <h3 className="text-sm sm:text-base font-semibold text-foreground">{mod.title}</h3>
                              {modCompleted === modSteps && modSteps > 0 && (
                                <Badge className="bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400 text-[10px]">
                                  Complete
                                </Badge>
                              )}
                            </div>
                            <p className="text-xs text-muted-foreground mt-0.5">{mod.description}</p>
                            <div className="mt-2 flex items-center gap-2">
                              <Progress value={modProgress} className="flex-1 h-1.5" />
                              <span className="text-[10px] text-muted-foreground">{modCompleted}/{modSteps}</span>
                            </div>
                          </div>
                          <ChevronDown className={`h-5 w-5 text-muted-foreground transition-transform shrink-0 ${isOpen ? 'rotate-180' : ''}`} />
                        </div>
                      </CollapsibleTrigger>

                      <CollapsibleContent>
                        <div className="border-t border-border/30">
                          {mod.steps.map((step, si) => {
                            const stepKey = `${currentTrack.role}-${mi}-${si}`;
                            const done = completedSteps.has(stepKey);
                            const StIcon = step.icon;

                            return (
                              <div key={si} className={`flex items-start gap-3 px-4 sm:px-6 py-4 border-b border-border/15 last:border-b-0 transition-colors ${done ? 'bg-emerald-50/40 dark:bg-emerald-950/10' : ''}`}>
                                <button
                                  onClick={() => toggleStep(stepKey)}
                                  className="shrink-0 mt-0.5"
                                  aria-label={done ? 'Mark incomplete' : 'Mark complete'}
                                >
                                  {done ? (
                                    <CheckCircle2 className="h-6 w-6 text-emerald-500" />
                                  ) : (
                                    <Circle className="h-6 w-6 text-border hover:text-primary transition-colors" />
                                  )}
                                </button>
                                <div className="flex-1 min-w-0">
                                  <div className="flex items-center gap-2 mb-0.5">
                                    <StIcon className="h-4 w-4 text-primary/70 shrink-0" />
                                    <h4 className={`text-sm font-semibold ${done ? 'text-muted-foreground line-through' : 'text-foreground'}`}>
                                      {step.title}
                                    </h4>
                                  </div>
                                  <div className="ml-6 space-y-1.5">
                                    <div className="flex items-start gap-1.5">
                                      <ChevronRight className="h-3.5 w-3.5 text-primary mt-0.5 shrink-0" />
                                      <p className="text-sm font-medium text-primary/90">{step.action}</p>
                                    </div>
                                    <p className="text-xs text-muted-foreground leading-relaxed">{step.detail}</p>
                                    {step.tip && (
                                      <div className="flex items-start gap-1.5 mt-2 px-2.5 py-1.5 rounded-lg bg-amber-50 dark:bg-amber-950/20 border border-amber-200/50 dark:border-amber-800/30">
                                        <Star className="h-3.5 w-3.5 text-amber-500 mt-0.5 shrink-0" />
                                        <p className="text-xs text-amber-800 dark:text-amber-300">{step.tip}</p>
                                      </div>
                                    )}
                                  </div>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </CollapsibleContent>
                    </Card>
                  </Collapsible>
                );
              })}
            </div>
          </div>
        )}

        {/* Bottom CTA */}
        <div className="text-center py-6 space-y-3 border-t border-border/30">
          <p className="text-muted-foreground text-sm">
            Still have questions? Your BCBA or administrator can help.
          </p>
          <div className="flex items-center justify-center gap-3">
            <Button variant="outline" onClick={() => navigate('/tour')} className="gap-1.5">
              <ArrowLeft className="h-4 w-4" />
              Back to Tour
            </Button>
            <Button onClick={() => navigate('/login')} className="gap-1.5">
              <LogIn className="h-4 w-4" />
              Sign In
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FAQTutorial;
