import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible';
import {
  Zap,
  LogIn,
  Search,
  ArrowLeft,
  BarChart3,
  Star,
  Users,
  Shield,
  MessageCircle,
  Target,
  Gift,
  Gamepad2,
  BookOpen,
  Settings,
  FileText,
  Clock,
  HelpCircle,
  ChevronRight,
  ChevronDown,
  GraduationCap,
  UserCog,
  Heart,
  CheckCircle2,
  Circle,
  Megaphone,
  Eye,
  Smartphone,
  Bell,
  AlertTriangle,
  LayoutDashboard,
  UserPlus,
  Send,
  TrendingUp,
} from 'lucide-react';

/* ═══════════════════════════════════════════════════════════ */
/*  FAQ DATA                                                  */
/* ═══════════════════════════════════════════════════════════ */

interface FAQItem { q: string; a: string }
interface FAQSection { title: string; icon: React.ElementType; items: FAQItem[] }

const faqSections: FAQSection[] = [
  {
    title: 'Getting Started',
    icon: BookOpen,
    items: [
      { q: 'How do I log in to Beacon?', a: "Navigate to the sign-in page and enter your email and password. If your administrator has set up your account, you'll be taken directly to your Classroom view. If you don't have an account yet, ask your BCBA or admin for an invite code." },
      { q: 'What is an invite code and how do I use it?', a: "An invite code is a one-time or multi-use code generated by your administrator. Go to the Join page, enter the code, and your account will automatically be linked to the correct agency, classroom, and role." },
      { q: 'I logged in but see "Access Not Configured" — what do I do?', a: "This means your account hasn't been linked to an agency yet. Ask your administrator or BCBA to add your email to the system and assign you to the correct agency and app. Then click the Retry button on the blocked screen." },
      { q: 'Can I use Beacon on my phone?', a: 'Yes! Beacon is a Progressive Web App (PWA). On your phone, open the app in your browser, then tap "Add to Home Screen" from the browser menu. It will look and feel like a native app with offline support.' },
      { q: 'How do I install the app on my device?', a: 'Visit the Install page from the Settings menu. Follow the step-by-step instructions for your device (iOS or Android). The app installs directly from your browser — no app store needed.' },
    ],
  },
  {
    title: 'Classroom View',
    icon: Users,
    items: [
      { q: 'What is the Classroom View?', a: "The Classroom View is your home screen. It shows all students in your classroom with their attendance status, current location/presence, assigned staff, and live Beacon Point balances." },
      { q: 'How do I take attendance?', a: "From the Classroom View, tap any student's attendance indicator (the colored dot). Select Present, Absent, Tardy, or Early Dismissal. The change saves instantly." },
      { q: 'What is student presence vs. attendance?', a: 'Attendance tracks whether a student is in school for the day. Presence tracks where they are right now — in the classroom, at a pull-out, in the bathroom, etc.' },
      { q: 'How do I assign staff to students?', a: "In the Classroom View, tap on a student's staff assignment area. Select the available staff member from the dropdown. This updates in real time." },
      { q: "What are the Who's Here and Staff Presence panels?", a: "Who's Here shows a quick count of present vs. absent students. Staff Presence shows which staff members are in the room, on break, or at a different location. Both update in real time." },
    ],
  },
  {
    title: 'Data Collection',
    icon: BarChart3,
    items: [
      { q: 'What types of data can I collect?', a: 'Beacon supports Frequency (counting occurrences), Duration (timing how long something lasts), ABC (Antecedent-Behavior-Consequence logs), and Engagement Sampling (on-task/off-task checks at intervals).' },
      { q: 'How does Quick Add work?', a: 'Quick Add is a one-tap counter for common behaviors. Select a student, choose a behavior, and tap +. Each tap records one occurrence with a timestamp.' },
      { q: 'How do I log an ABC entry?', a: 'From the Data Collection page, select a student and tap ABC Log. Fill in the Antecedent, Behavior, and Consequence. You can also add intensity, duration, and notes.' },
      { q: 'What are Engagement Prompts?', a: 'Engagement Prompts are timed reminders that pop up at intervals you set. When the prompt appears, simply tap On Task or Off Task.' },
      { q: 'Can I collect data for multiple students at once?', a: 'Yes! The Bulk Award panel lets you award points to multiple students simultaneously. For individual data, quickly switch between students using the selector.' },
      { q: 'What happens to the data I collect?', a: 'All data is saved instantly to the cloud. Your BCBA can view it in real time, and it feeds into weekly trend charts and summary reports.' },
      { q: 'Can a substitute teacher collect data?', a: 'Yes! Generate a Guest Access Code from the Classroom Manager. The substitute enters this code on any device — no login needed.' },
    ],
  },
  {
    title: 'Engagement & Skill Probes',
    icon: Target,
    items: [
      { q: 'What is Engagement Sampling?', a: "Engagement Sampling uses timed intervals to check whether a student is on-task or off-task. Over time, this builds percentage-based engagement data that's invaluable for BCBAs." },
      { q: 'What are Skill Probes?', a: 'Skill Probes let you quickly test a student on specific IEP targets. Mark whether they demonstrated the skill independently, with prompting, or not at all.' },
      { q: 'Can I snooze a prompt?', a: "Yes! Tap Snooze on any engagement prompt. It will come back after a configurable delay. This ensures data collection doesn't interfere with instruction." },
      { q: 'How do interval settings work?', a: 'Go to Settings or ask your BCBA to configure intervals. You can set the interval length (1-30 minutes), active hours, specific days, and scope.' },
    ],
  },
  {
    title: 'Beacon Points\u2122',
    icon: Star,
    items: [
      { q: 'What are Beacon Points?', a: 'Beacon Points are a real-time token economy system. Students earn points for positive behaviors, engagement, and completing tasks. Points can be spent in the Reward Store.' },
      { q: 'How do students earn points?', a: 'Points are earned three ways: (1) Automatically via point rules, (2) Manually with one tap, (3) Bulk Awards for the entire class.' },
      { q: 'What is Response Cost?', a: 'Response Cost deducts points for specific behaviors. It must be enabled per student by the BCBA.' },
      { q: 'How do Token Boards work?', a: "Token Boards visualize a student's progress toward a point goal. As they earn points, tokens fill up on their board." },
      { q: 'Can I reset points?', a: 'Yes. Reset points for individual students or the entire class from the Beacon Points controls.' },
      { q: 'How do Point Rules work?', a: 'Point Rules define how many points are awarded or deducted for specific events. Rules can be linked to specific data types.' },
    ],
  },
  {
    title: 'Reward Store',
    icon: Gift,
    items: [
      { q: 'What is the Reward Store?', a: 'The Reward Store is where students spend their Beacon Points. Teachers create rewards with point costs, categories, stock limits, and images.' },
      { q: 'How do I create a reward?', a: 'Go to the Rewards page and tap Add Reward. Enter a name, point cost, category, and optional description.' },
      { q: 'What are Sponsored Rewards?', a: 'Sponsored Rewards are special items added by administrators or partners with a Sponsored badge.' },
      { q: 'Can students redeem rewards themselves?', a: 'Yes! Through the Student Portal, students browse and request redemption. Teachers approve or deny the request.' },
    ],
  },
  {
    title: 'Game Board & Avatars',
    icon: Gamepad2,
    items: [
      { q: 'What is the Game Board?', a: "The Game Board is a visual display for smartboard projection. It shows a race track where each student's avatar advances based on their points." },
      { q: 'How do avatars work?', a: 'Each student selects a starting avatar. As they earn more points, they unlock new avatar options.' },
      { q: 'Can I project the Game Board on a smartboard?', a: 'Absolutely! Open the board URL on any browser connected to your smartboard. It updates in real time.' },
      { q: 'How do class goals work?', a: 'Set a class-wide point goal. The Game Board shows a progress bar filling up as the whole class earns points together.' },
    ],
  },
  {
    title: 'Communication',
    icon: MessageCircle,
    items: [
      { q: 'What are Threads?', a: 'Threads are team-based message channels. Create public threads for your whole classroom team or private threads for specific staff members.' },
      { q: 'What is the Inbox?', a: 'The Inbox is for more formal, structured messages between staff. Messages can include attachments and be pinned to specific students.' },
      { q: 'What are Parent Snapshots?', a: "Parent Snapshots are secure, read-only links showing a student's daily highlights. Parents view them in their browser without needing an account." },
      { q: 'How do I send a Parent Snapshot?', a: "From the student's detail page, tap Parent Snapshot. Share the generated link via text or email." },
      { q: 'Can parents respond to messages?', a: 'Parent Snapshots are read-only. For two-way communication, your school may use the Behavior Decoded parent companion app.' },
    ],
  },
  {
    title: 'Safety & Mayday',
    icon: Shield,
    items: [
      { q: 'What is the MAYDAY button?', a: 'The MAYDAY button is an emergency alert system. Press it to instantly notify your supervisors and admin team that you need support.' },
      { q: 'Who receives MAYDAY alerts?', a: 'MAYDAY alerts go to all configured Mayday Contacts for your agency — typically BCBAs, program directors, and on-call supervisors.' },
      { q: 'What urgency levels are available?', a: 'Three levels: Urgent (immediate physical safety concern), High (escalating situation), and Standard (non-emergency support request).' },
      { q: 'Can I cancel a MAYDAY alert?', a: 'Yes. After sending, you can resolve or cancel the alert. This updates all recipients immediately.' },
    ],
  },
  {
    title: 'IEP Tools',
    icon: FileText,
    items: [
      { q: 'What is the IEP Reader?', a: 'The IEP Reader lets you upload IEP documents (PDF). Beacon uses AI to extract goals, accommodations, services, and progress data.' },
      { q: 'What is the IEP Writer?', a: "The IEP Writer helps generate IEP goals, FBA narratives, and BIP documents using AI, pulling from the student's collected data." },
      { q: 'Do I need to be a BCBA to use the IEP tools?', a: 'No! Teachers can upload IEPs and view extracted information. Approving goals and generating clinical documents is typically reserved for BCBAs.' },
    ],
  },
  {
    title: 'Classroom Management',
    icon: Settings,
    items: [
      { q: 'How do I set up a new classroom?', a: 'Go to the Classroom Manager. Tap Create Classroom and enter a name, school, and grade band. Then add students and assign staff.' },
      { q: 'Can I be assigned to multiple classrooms?', a: 'Yes! Use the classroom selector to switch between them. Your data and settings are maintained separately.' },
      { q: 'How do I add students to my classroom?', a: 'In the Classroom Manager, select your classroom and tap Add Students. Choose from the students assigned to your agency.' },
      { q: 'What staff roles are available?', a: 'Teacher, Behavior Interventionist (BI), Aide, BCBA, SPED, SLP, OT, and Other. Each shows as a role badge.' },
      { q: 'How do Guest Access Codes work?', a: 'Guest Access Codes are temporary, time-limited codes for substitute teachers. Generate one from the Classroom Manager.' },
    ],
  },
  {
    title: 'Reports & Data',
    icon: BarChart3,
    items: [
      { q: 'What reports are available?', a: 'Weekly Data Summaries, Parent Reports, and detailed data exports. All pull from your real-time data.' },
      { q: 'How do Weekly Trend Charts work?', a: 'Trend Charts automatically graph your collected data over time — frequency trends, duration averages, engagement percentages, and ABC patterns.' },
      { q: 'Can I export data?', a: 'Data can be viewed in-app through summaries and trend charts. Your BCBA or administrator can access full data through the admin dashboard.' },
    ],
  },
  {
    title: 'Account & Settings',
    icon: Settings,
    items: [
      { q: 'How do I change my notification settings?', a: "Go to Settings \u2192 Notifications. Toggle engagement prompts, data log reminders, escalation alerts, and more. Set quiet hours for off-school times." },
      { q: 'How do I reset my password?', a: "From the login page, tap Forgot Password. Enter your email and you'll receive a reset link." },
      { q: 'Can I switch between agencies or workspaces?', a: "If you belong to multiple agencies, you'll see a Workspace Selector when you log in." },
      { q: 'What data can my BCBA see?', a: 'Your BCBA can see all collected data — frequency counts, duration logs, ABC entries, engagement checks, and skill probes. They cannot see your personal settings.' },
    ],
  },
];

/* ═══════════════════════════════════════════════════════════ */
/*  GENERIC TUTORIALS (kept from before)                      */
/* ═══════════════════════════════════════════════════════════ */

interface TutorialStep { step: number; title: string; description: string; icon: React.ElementType }
interface TutorialSection { title: string; description: string; steps: TutorialStep[] }

const tutorials: TutorialSection[] = [
  {
    title: 'Your First Day with Beacon',
    description: 'A step-by-step guide to get through your first school day using Beacon.',
    steps: [
      { step: 1, title: 'Sign in & check your Classroom', description: "Log in and navigate to the Classroom View. You'll see your assigned students, their attendance from yesterday, and any staff notes.", icon: Users },
      { step: 2, title: 'Take morning attendance', description: "Tap each student's attendance indicator to mark them Present, Absent, or Tardy. This takes about 30 seconds for a full class.", icon: Clock },
      { step: 3, title: 'Start data collection', description: 'Open Quick Add for your first student. Tap the behavior buttons as you observe them during morning routine.', icon: BarChart3 },
      { step: 4, title: 'Award Beacon Points', description: 'When students follow routines, award points manually with one tap or let auto-rules handle it.', icon: Star },
      { step: 5, title: 'Check engagement prompts', description: "If your BCBA has set up interval prompts, they'll pop up during instruction. Just tap On Task or Off Task.", icon: Target },
      { step: 6, title: 'Send a Parent Snapshot', description: 'At the end of the day, generate a Parent Snapshot link for any student. Share via text — families love the positive highlights!', icon: MessageCircle },
    ],
  },
  {
    title: 'Setting Up Your Classroom',
    description: 'How to configure your classroom for the first time.',
    steps: [
      { step: 1, title: 'Create your classroom group', description: 'Go to Classroom Manager from the More menu. Tap Create Classroom and enter a name, school name, and grade band.', icon: Users },
      { step: 2, title: 'Add students', description: 'Select your classroom and tap Add Students. Pick students from your agency roster.', icon: BookOpen },
      { step: 3, title: 'Assign staff', description: 'Add yourself and any co-teachers, BIs, or aides. Select the correct role for each person.', icon: Users },
      { step: 4, title: 'Configure the Game Board', description: 'Go to Board Settings and set your classroom slug, mission text, word of the week, and class goal.', icon: Gamepad2 },
      { step: 5, title: 'Set up rewards', description: 'Go to the Rewards page and add at least 3-5 rewards with different point costs.', icon: Gift },
    ],
  },
  {
    title: 'Running an Effective Data Day',
    description: 'Best practices for consistent, high-quality data collection.',
    steps: [
      { step: 1, title: 'Check your targets', description: 'Review which behaviors and skills you are tracking today.', icon: Target },
      { step: 2, title: 'Use Quick Add for frequency', description: 'For behaviors that happen frequently, keep Quick Add open. One tap per occurrence.', icon: BarChart3 },
      { step: 3, title: 'Time durations when needed', description: 'For behaviors with duration, use the timer. Tap start when it begins, stop when it ends.', icon: Clock },
      { step: 4, title: 'Log ABC for significant incidents', description: 'When a notable behavior occurs, log the full ABC for functional analysis context.', icon: FileText },
      { step: 5, title: 'Respond to engagement prompts', description: 'When prompted, take a quick scan and tap On Task or Off Task. Consistency matters.', icon: Target },
      { step: 6, title: 'End-of-day review', description: 'Check the data summary to make sure nothing was missed. Add notes while the day is fresh.', icon: BookOpen },
    ],
  },
];

/* ═══════════════════════════════════════════════════════════ */
/*  ROLE-BASED TRAINING TRACKS                                */
/* ═══════════════════════════════════════════════════════════ */

interface TrackStep {
  title: string;
  action: string;
  detail: string;
  icon: React.ElementType;
  tip?: string;
}

interface TrackModule {
  title: string;
  description: string;
  icon: React.ElementType;
  steps: TrackStep[];
}

interface RoleTrack {
  role: string;
  label: string;
  emoji: string;
  color: string;
  icon: React.ElementType;
  description: string;
  modules: TrackModule[];
}

const roleTracks: RoleTrack[] = [
  {
    role: 'teacher',
    label: 'Teacher',
    emoji: '\uD83D\uDC69\u200D\uD83C\uDFEB',
    color: 'bg-emerald-500',
    icon: GraduationCap,
    description: 'Everything you need to run a Beacon-powered classroom from day one.',
    modules: [
      {
        title: 'First Day Setup',
        description: 'Get your classroom ready in under 10 minutes.',
        icon: Smartphone,
        steps: [
          { title: 'Install Beacon on your device', action: 'Open Beacon in Safari/Chrome \u2192 Tap Share \u2192 Add to Home Screen', detail: 'This gives you a native-app experience with offline support and push notifications.', icon: Smartphone, tip: 'Pin it right next to your most-used apps so it becomes part of your routine.' },
          { title: 'Sign in with your credentials', action: 'Enter the email and password your admin provided', detail: 'If you received an invite code instead, go to the Join page and enter the code first.', icon: LogIn },
          { title: 'Check your Classroom View', action: 'Tap Classroom in the bottom nav', detail: "You should see your students listed with yesterday's attendance. If the list is empty, contact your admin.", icon: Users, tip: 'This screen is your home base \u2014 you will start here every morning.' },
          { title: 'Take your first attendance', action: "Tap each student's colored dot \u2192 Select Present, Absent, or Tardy", detail: 'Changes save instantly and are visible to your whole team. Takes about 30 seconds for a full class.', icon: CheckCircle2 },
          { title: 'Open the Game Board on your smartboard', action: 'Navigate to Board Settings \u2192 Copy the board URL \u2192 Open on your display', detail: 'Students will see their avatars, points, and class goal in real time. No refreshing needed!', icon: Gamepad2, tip: 'Bookmark the board URL on your smartboard browser for one-click access each morning.' },
        ],
      },
      {
        title: 'Running a Classroom',
        description: 'Your daily Beacon workflow from bell to bell.',
        icon: Users,
        steps: [
          { title: 'Morning: Take attendance', action: 'Classroom View \u2192 Tap attendance dots for each student', detail: 'Mark Present, Absent, Tardy, or Early Dismissal. Staff Presence updates automatically.', icon: CheckCircle2 },
          { title: 'Update student presence throughout the day', action: 'Tap a student \u2192 Change location (Classroom, Pull-out, Bathroom, etc.)', detail: 'Presence tracking lets your team know where every student is at all times.', icon: Eye },
          { title: 'Log behaviors as they happen', action: 'Quick Add \u2192 Select student \u2192 Tap behavior button', detail: 'Each tap records one occurrence with an automatic timestamp. Use the \u2013 button to correct mistakes.', icon: BarChart3 },
          { title: 'Respond to engagement prompts', action: 'When the prompt pops up \u2192 Tap On Task or Off Task', detail: 'Takes 2 seconds. If you are mid-instruction, tap Snooze and it will come back shortly.', icon: Target, tip: 'Consistency over perfection. Even partial engagement data is valuable for your BCBA.' },
          { title: 'End-of-day: Send parent snapshots', action: 'Student Detail \u2192 Parent Snapshot \u2192 Share link', detail: 'Families see a positive summary of the day. You can share via text, email, or any messaging app.', icon: Send },
        ],
      },
      {
        title: 'Using Points & Token Board',
        description: 'Maximize your token economy throughout the day.',
        icon: Star,
        steps: [
          { title: 'Award points for positive behavior', action: 'Tap the + button on any student \u2192 Enter points \u2192 Done', detail: 'Points appear instantly on the Game Board. Students love watching their avatars advance!', icon: Star },
          { title: 'Use Bulk Award for class-wide recognition', action: 'Classroom View \u2192 Bulk Award \u2192 Select students \u2192 Enter points', detail: 'Perfect for transitions, group activities, or rewarding the whole class at once.', icon: Users },
          { title: 'Monitor token boards', action: 'Check the Game Board or individual student cards', detail: 'Tokens fill up as students approach their goal. When full, they have earned their reward!', icon: Gamepad2, tip: 'Narrate the progress aloud: "Jamie only needs 5 more points to reach the goal!"' },
          { title: 'Let students redeem rewards', action: 'Students browse the Reward Store \u2192 Request redemption \u2192 You approve', detail: 'This builds self-management skills. You can also manually redeem for younger students.', icon: Gift },
        ],
      },
      {
        title: 'Sending Mayday',
        description: 'Get immediate support when you need it most.',
        icon: AlertTriangle,
        steps: [
          { title: 'Locate the Mayday button', action: 'Bottom of the Classroom View \u2192 Red MAYDAY button', detail: 'The button is always accessible from your main screen \u2014 no navigation needed.', icon: AlertTriangle },
          { title: 'Select urgency and send', action: 'Choose Urgent / High / Standard \u2192 Add optional note \u2192 Send', detail: 'All configured contacts receive the alert immediately via email and in-app notification.', icon: Megaphone, tip: "Do not hesitate to use it. That is exactly what it is for. Your safety team wants to know." },
          { title: 'Wait for acknowledgment', action: 'The alert status updates in real time as contacts respond', detail: 'You can also resolve or cancel the alert once the situation is handled.', icon: CheckCircle2 },
        ],
      },
      {
        title: 'Messaging Staff',
        description: 'Coordinate with your team without leaving the app.',
        icon: MessageCircle,
        steps: [
          { title: 'Start or join a Thread', action: 'Threads tab \u2192 Create New or tap an existing thread', detail: 'Use public threads for team-wide updates and private threads for sensitive topics.', icon: MessageCircle },
          { title: 'Send a message', action: 'Type your message \u2192 Tap Send', detail: 'Messages are delivered instantly. You can include @mentions and attach images.', icon: Send },
          { title: 'Use the Inbox for formal messages', action: 'Inbox tab \u2192 Compose \u2192 Add recipients and attachments', detail: 'Inbox messages can be pinned to specific students for reference.', icon: FileText, tip: 'Use Threads for quick coordination, Inbox for things that need to be found later.' },
        ],
      },
      {
        title: 'Messaging Parents',
        description: 'Keep families informed with zero effort.',
        icon: Heart,
        steps: [
          { title: 'Generate a Parent Snapshot', action: 'Student Detail \u2192 Tap Parent Snapshot', detail: 'Beacon creates a secure, time-limited link with daily highlights, points, and positive notes.', icon: Eye },
          { title: 'Share the link', action: 'Copy the link \u2192 Send via text, email, or school messaging platform', detail: 'Parents open it in any browser \u2014 no account or app download required.', icon: Send },
          { title: 'Review what parents see', action: 'Tap Preview to see the snapshot before sharing', detail: 'The snapshot focuses on positive highlights and progress. Parents love it!', icon: Heart, tip: 'Sending a snapshot at the end of a great day builds trust and parent engagement.' },
        ],
      },
    ],
  },
  {
    role: 'admin',
    label: 'Admin / BCBA',
    emoji: '\uD83D\uDC69\u200D\uD83D\uDCBC',
    color: 'bg-blue-500',
    icon: UserCog,
    description: 'Set up and manage Beacon for your team — classrooms, staff, students, and safety.',
    modules: [
      {
        title: 'Creating Classrooms',
        description: 'Set up classroom groups for your staff.',
        icon: LayoutDashboard,
        steps: [
          { title: 'Open Classroom Manager', action: 'More menu \u2192 Classroom Manager', detail: 'This is where you create, edit, and manage all classroom groups for your agency.', icon: LayoutDashboard },
          { title: 'Create a new classroom', action: 'Tap Create Classroom \u2192 Enter name, school, grade band', detail: 'Use descriptive names like "Room 12 \u2014 Ms. Rivera" so staff can find theirs easily.', icon: Users },
          { title: 'Set the board slug', action: 'Edit classroom \u2192 Set a URL-friendly slug', detail: 'This creates a shareable URL for the Game Board (e.g., /board/room-12).', icon: Gamepad2, tip: 'Keep slugs short and memorable for easy smartboard setup.' },
        ],
      },
      {
        title: 'Assigning Staff',
        description: 'Add teachers, BIs, aides, and specialists to classrooms.',
        icon: UserPlus,
        steps: [
          { title: 'Select the classroom', action: 'Classroom Manager \u2192 Tap the classroom', detail: 'You will see the current student roster and staff assignments.', icon: Users },
          { title: 'Add staff members', action: 'Tap Add Staff \u2192 Search by name \u2192 Select role', detail: 'Available roles: Teacher, BI, Aide, BCBA, SPED, SLP, OT, Other.', icon: UserPlus },
          { title: 'Verify role badges', action: 'Check the Classroom View to confirm badges display correctly', detail: 'Each staff member shows their role badge so the team knows who is who.', icon: CheckCircle2, tip: 'Staff can be assigned to multiple classrooms with different roles.' },
        ],
      },
      {
        title: "Managing Who's Here",
        description: 'Real-time visibility into student and staff presence.',
        icon: Eye,
        steps: [
          { title: "Open Who's Here panel", action: "Classroom View \u2192 Who's Here section", detail: 'See a live count of present vs. absent students with visual indicators.', icon: Eye },
          { title: 'View Staff Presence', action: 'Scroll to Staff Presence panel', detail: 'See which staff are in-room, on break, or at another location.', icon: Users },
          { title: 'Update a student location', action: 'Tap student \u2192 Change presence (Classroom, Pull-out, Bathroom, etc.)', detail: 'The entire team sees updates instantly. Great for safety accountability.', icon: Target, tip: 'During drills, quickly verify all student locations from this panel.' },
        ],
      },
      {
        title: 'Configuring Mayday Contacts',
        description: 'Ensure emergency alerts reach the right people.',
        icon: Shield,
        steps: [
          { title: 'Open Mayday Contacts Manager', action: 'Settings or Admin Dashboard \u2192 Mayday Contacts', detail: 'This is where you define who receives MAYDAY alerts for your agency.', icon: Shield },
          { title: 'Add a contact', action: 'Tap Add Contact \u2192 Enter name, email, phone \u2192 Set notification channels', detail: 'Choose whether they receive alerts via email, SMS, in-app, or all three.', icon: UserPlus },
          { title: 'Set availability and overrides', action: 'Configure opt-out days, admin override, and active status', detail: 'Contacts can be deactivated during vacation without removing them.', icon: Settings, tip: 'Always have at least 2 active contacts configured for safety redundancy.' },
        ],
      },
      {
        title: 'Viewing Reports',
        description: 'Access data summaries and trends across your team.',
        icon: TrendingUp,
        steps: [
          { title: 'Open Weekly Data Summary', action: 'Data Summary page \u2192 Select student and date range', detail: 'See auto-generated trend charts for frequency, duration, and engagement.', icon: BarChart3 },
          { title: 'Generate Parent Reports', action: 'Parent Reports page \u2192 Select student \u2192 Generate', detail: 'Family-friendly summaries with highlights and progress notes.', icon: FileText },
          { title: 'Review IEP data linkage', action: 'IEP Reader \u2192 View extracted goals alongside collected data', detail: 'Match IEP goals to real behavior data for evidence-based progress monitoring.', icon: BookOpen, tip: 'Use trend data in IEP meetings to show concrete progress with visuals.' },
        ],
      },
    ],
  },
  {
    role: 'parent',
    label: 'Parent / Family',
    emoji: '\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67',
    color: 'bg-purple-500',
    icon: Heart,
    description: 'Stay connected to your child\'s classroom experience \u2014 no app download needed.',
    modules: [
      {
        title: 'Viewing Child Progress',
        description: "See your child's daily highlights and point balance.",
        icon: Eye,
        steps: [
          { title: 'Open the snapshot link', action: 'Tap the link your teacher shared via text or email', detail: 'The link opens in any browser \u2014 no login or app download required.', icon: Smartphone },
          { title: 'Review daily highlights', action: 'Scroll through the summary card', detail: 'You will see points earned, positive behaviors, and any teacher notes for the day.', icon: Star },
          { title: 'Check the points balance', action: 'View the current point total and recent transactions', detail: 'Points represent your child earning recognition for positive classroom behavior.', icon: TrendingUp, tip: 'Ask your child about their points! It reinforces the positive behavior at home too.' },
        ],
      },
      {
        title: 'Understanding Rewards',
        description: 'How the Beacon Points reward system works.',
        icon: Gift,
        steps: [
          { title: 'Points = classroom currency', action: 'Your child earns points for following rules, staying on task, and positive interactions', detail: 'The teacher awards points throughout the day. Some points are automatic, others are manual recognition.', icon: Star },
          { title: 'Rewards are earned, not given', action: 'Students choose rewards from the Reward Store when they have enough points', detail: 'Rewards include extra free time, special activities, small tangible items, and more.', icon: Gift },
          { title: 'Token boards show progress', action: 'On the classroom Game Board, your child has an avatar that advances as they earn points', detail: "It's a fun, visual motivator that the whole class can see on the smartboard.", icon: Gamepad2, tip: 'Celebrate milestones together! When your child reaches a goal, acknowledge it at home.' },
        ],
      },
      {
        title: 'Messaging Teacher',
        description: 'How communication works between school and home.',
        icon: MessageCircle,
        steps: [
          { title: 'Parent Snapshots are read-only', action: 'Snapshots are one-way summaries designed to share positive highlights', detail: 'They focus on what went well so families see the positive side of the school day.', icon: Eye },
          { title: 'For questions, contact the teacher directly', action: 'Use your existing school communication channel (email, phone, app)', detail: 'Beacon focuses on data and classroom management. Family communication uses your school\'s standard channels.', icon: MessageCircle },
          { title: 'Ask about Behavior Decoded', action: 'The companion parent app provides two-way communication features', detail: 'Ask your teacher or BCBA if your school uses Behavior Decoded for parent engagement.', icon: Smartphone, tip: 'Regular communication with your child\'s teacher makes the biggest impact on progress.' },
        ],
      },
      {
        title: 'Reading Updates',
        description: 'Understanding the information shared with you.',
        icon: FileText,
        steps: [
          { title: 'What you see in a snapshot', action: 'Points earned, positive behavior highlights, daily summary', detail: 'Snapshots are curated to show progress and wins. They are generated by the teacher at the end of the day.', icon: Eye },
          { title: 'Understanding behavior data', action: 'If shared, you may see trend charts showing progress over weeks', detail: 'Upward trends in positive behaviors and downward trends in challenging behaviors show growth.', icon: TrendingUp },
          { title: 'IEP progress updates', action: 'During IEP meetings, your BCBA may share Beacon data visuals', detail: 'These charts are generated from real classroom data collected daily by your child\'s team.', icon: BookOpen, tip: 'Keep snapshots \u2014 they make great conversation starters at parent-teacher conferences!' },
        ],
      },
    ],
  },
];

/* ═══════════════════════════════════════════════════════════ */
/*  COMPONENT                                                 */
/* ═══════════════════════════════════════════════════════════ */

type TabKey = 'faq' | 'tutorials' | 'tracks';

const FAQTutorial = () => {
  const navigate = useNavigate();
  const [search, setSearch] = useState('');
  const [activeTab, setActiveTab] = useState<TabKey>('faq');
  const [activeTrack, setActiveTrack] = useState<string>('teacher');
  const [completedSteps, setCompletedSteps] = useState<Set<string>>(new Set());
  const [expandedModules, setExpandedModules] = useState<Set<string>>(new Set());

  const toggleStep = (key: string) => {
    setCompletedSteps((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  const toggleModule = (key: string) => {
    setExpandedModules((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  const filteredSections = faqSections
    .map((section) => ({
      ...section,
      items: section.items.filter(
        (item) =>
          item.q.toLowerCase().includes(search.toLowerCase()) ||
          item.a.toLowerCase().includes(search.toLowerCase()),
      ),
    }))
    .filter((section) => section.items.length > 0);

  const totalQuestions = faqSections.reduce((sum, s) => sum + s.items.length, 0);
  const currentTrack = roleTracks.find((t) => t.role === activeTrack) || roleTracks[0];
  const totalTrackSteps = currentTrack.modules.reduce((sum, m) => sum + m.steps.length, 0);
  const completedTrackSteps = currentTrack.modules.reduce(
    (sum, m, mi) =>
      sum + m.steps.filter((_, si) => completedSteps.has(`${currentTrack.role}-${mi}-${si}`)).length,
    0,
  );
  const trackProgress = totalTrackSteps > 0 ? Math.round((completedTrackSteps / totalTrackSteps) * 100) : 0;

  const tabs: { key: TabKey; label: string; icon: React.ElementType }[] = [
    { key: 'faq', label: 'FAQ', icon: HelpCircle },
    { key: 'tutorials', label: 'Tutorials', icon: BookOpen },
    { key: 'tracks', label: 'Training Tracks', icon: GraduationCap },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-background via-background to-muted/30">
      {/* Top bar */}
      <div className="sticky top-0 z-50 bg-card/80 backdrop-blur-md border-b border-border/50">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="icon" onClick={() => navigate('/tour')} className="shrink-0">
              <ArrowLeft className="h-4 w-4" />
            </Button>
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <Zap className="h-4 w-4 text-primary-foreground" />
            </div>
            <span className="font-bold text-foreground text-lg">Beacon</span>
            <Badge variant="secondary" className="text-[10px] ml-1">Help Center</Badge>
          </div>
          <Button size="sm" onClick={() => navigate('/login')} className="gap-1.5">
            <LogIn className="h-4 w-4" />
            <span className="hidden sm:inline">Sign In</span>
          </Button>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8 space-y-8">
        {/* Header */}
        <div className="text-center space-y-3">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary text-xs font-medium">
            <HelpCircle className="h-3.5 w-3.5" />
            {totalQuestions} questions · 3 training tracks
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-foreground">
            Help Center & Training
          </h1>
          <p className="text-muted-foreground text-base max-w-xl mx-auto">
            Everything you need — from quick answers to guided, step-by-step training for your role.
          </p>
        </div>

        {/* Tab toggle */}
        <div className="flex items-center justify-center gap-1 p-1 bg-muted rounded-xl w-fit mx-auto">
          {tabs.map((tab) => {
            const TIcon = tab.icon;
            return (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className={`px-4 sm:px-5 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-1.5 ${
                  activeTab === tab.key
                    ? 'bg-card text-foreground shadow-sm'
                    : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                <TIcon className="h-4 w-4" />
                <span className="hidden sm:inline">{tab.label}</span>
                <span className="sm:hidden">{tab.label.split(' ')[0]}</span>
              </button>
            );
          })}
        </div>

        {/* ─── FAQ TAB ─── */}
        {activeTab === 'faq' && (
          <>
            <div className="relative max-w-md mx-auto">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input placeholder="Search questions\u2026" value={search} onChange={(e) => setSearch(e.target.value)} className="pl-10" />
            </div>

            {!search && (
              <div className="flex flex-wrap items-center justify-center gap-2">
                {faqSections.map((section) => {
                  const SIcon = section.icon;
                  return (
                    <a key={section.title} href={`#faq-${section.title.toLowerCase().replace(/\s+/g, '-')}`} className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium bg-muted text-muted-foreground hover:bg-muted/80 transition-all">
                      <SIcon className="h-3.5 w-3.5" />
                      {section.title}
                    </a>
                  );
                })}
              </div>
            )}

            <div className="space-y-6">
              {filteredSections.map((section) => {
                const SIcon = section.icon;
                return (
                  <div key={section.title} id={`faq-${section.title.toLowerCase().replace(/\s+/g, '-')}`} className="scroll-mt-20">
                    <div className="flex items-center gap-2 mb-3">
                      <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
                        <SIcon className="h-4 w-4 text-primary" />
                      </div>
                      <h2 className="text-lg font-semibold text-foreground">{section.title}</h2>
                      <Badge variant="outline" className="text-[10px] ml-auto">
                        {section.items.length} {section.items.length === 1 ? 'question' : 'questions'}
                      </Badge>
                    </div>
                    <Card className="border-border/50">
                      <CardContent className="p-0">
                        <Accordion type="multiple" className="w-full">
                          {section.items.map((item, i) => (
                            <AccordionItem key={i} value={`${section.title}-${i}`} className="border-border/30 last:border-b-0">
                              <AccordionTrigger className="px-4 py-3 text-sm font-medium text-foreground hover:no-underline text-left">
                                {item.q}
                              </AccordionTrigger>
                              <AccordionContent className="px-4 pb-4 text-sm text-muted-foreground leading-relaxed">
                                {item.a}
                              </AccordionContent>
                            </AccordionItem>
                          ))}
                        </Accordion>
                      </CardContent>
                    </Card>
                  </div>
                );
              })}
              {filteredSections.length === 0 && (
                <div className="text-center py-12">
                  <HelpCircle className="h-10 w-10 text-muted-foreground/30 mx-auto mb-3" />
                  <p className="text-muted-foreground">No questions match &quot;{search}&quot;</p>
                  <Button variant="link" size="sm" onClick={() => setSearch('')} className="mt-1">Clear search</Button>
                </div>
              )}
            </div>
          </>
        )}

        {/* ─── TUTORIALS TAB ─── */}
        {activeTab === 'tutorials' && (
          <div className="space-y-8">
            {tutorials.map((tutorial, tIdx) => (
              <Card key={tIdx} className="border-border/50 overflow-hidden">
                <div className="p-6 border-b border-border/30 bg-muted/30">
                  <div className="flex items-start gap-3">
                    <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0 mt-0.5">
                      <BookOpen className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-foreground">{tutorial.title}</h3>
                      <p className="text-sm text-muted-foreground mt-0.5">{tutorial.description}</p>
                    </div>
                  </div>
                </div>
                <CardContent className="p-0">
                  {tutorial.steps.map((step, sIdx) => {
                    const StepIcon = step.icon;
                    return (
                      <div key={sIdx} className="flex items-start gap-4 px-6 py-4 border-b border-border/20 last:border-b-0">
                        <div className="shrink-0 flex flex-col items-center gap-1">
                          <div className="w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-sm font-bold">
                            {step.step}
                          </div>
                          {sIdx < tutorial.steps.length - 1 && <div className="w-px h-full min-h-[16px] bg-border/40" />}
                        </div>
                        <div className="pt-1">
                          <div className="flex items-center gap-2 mb-1">
                            <StepIcon className="h-4 w-4 text-primary/70" />
                            <h4 className="text-sm font-semibold text-foreground">{step.title}</h4>
                          </div>
                          <p className="text-sm text-muted-foreground leading-relaxed">{step.description}</p>
                        </div>
                      </div>
                    );
                  })}
                </CardContent>
              </Card>
            ))}
          </div>
        )}

        {/* ─── TRAINING TRACKS TAB ─── */}
        {activeTab === 'tracks' && (
          <div className="space-y-6">
            {/* Role selector */}
            <div className="flex items-center justify-center gap-2 flex-wrap">
              {roleTracks.map((track) => {
                const TIcon = track.icon;
                return (
                  <button
                    key={track.role}
                    onClick={() => setActiveTrack(track.role)}
                    className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all border ${
                      activeTrack === track.role
                        ? 'bg-primary text-primary-foreground border-primary shadow-md'
                        : 'bg-card text-foreground border-border hover:border-primary/50'
                    }`}
                  >
                    <TIcon className="h-4 w-4" />
                    <span>{track.emoji} {track.label}</span>
                  </button>
                );
              })}
            </div>

            {/* Track header & progress */}
            <Card className="border-border/50 bg-gradient-to-r from-muted/50 to-muted/20">
              <CardContent className="p-6">
                <div className="flex items-start gap-4">
                  <div className={`w-12 h-12 rounded-2xl ${currentTrack.color} flex items-center justify-center shrink-0`}>
                    <currentTrack.icon className="h-6 w-6 text-white" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h2 className="text-xl font-bold text-foreground">
                      {currentTrack.emoji} {currentTrack.label} Track
                    </h2>
                    <p className="text-sm text-muted-foreground mt-1">{currentTrack.description}</p>
                    <div className="mt-3 flex items-center gap-3">
                      <Progress value={trackProgress} className="flex-1 h-2" />
                      <span className="text-xs font-medium text-muted-foreground whitespace-nowrap">
                        {completedTrackSteps}/{totalTrackSteps} steps
                      </span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Modules */}
            <div className="space-y-4">
              {currentTrack.modules.map((mod, mi) => {
                const modKey = `${currentTrack.role}-mod-${mi}`;
                const isOpen = expandedModules.has(modKey);
                const ModIcon = mod.icon;
                const modSteps = mod.steps.length;
                const modCompleted = mod.steps.filter((_, si) => completedSteps.has(`${currentTrack.role}-${mi}-${si}`)).length;
                const modProgress = modSteps > 0 ? Math.round((modCompleted / modSteps) * 100) : 0;

                return (
                  <Collapsible key={mi} open={isOpen} onOpenChange={() => toggleModule(modKey)}>
                    <Card className={`border-border/50 overflow-hidden transition-all ${modCompleted === modSteps && modSteps > 0 ? 'border-emerald-300/50 bg-emerald-50/30 dark:bg-emerald-950/10' : ''}`}>
                      <CollapsibleTrigger className="w-full text-left">
                        <div className="p-4 sm:p-5 flex items-center gap-3 hover:bg-muted/30 transition-colors">
                          <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
                            <ModIcon className="h-5 w-5 text-primary" />
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2">
                              <h3 className="text-sm sm:text-base font-semibold text-foreground">{mod.title}</h3>
                              {modCompleted === modSteps && modSteps > 0 && (
                                <Badge className="bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400 text-[10px]">
                                  Complete
                                </Badge>
                              )}
                            </div>
                            <p className="text-xs text-muted-foreground mt-0.5">{mod.description}</p>
                            <div className="mt-2 flex items-center gap-2">
                              <Progress value={modProgress} className="flex-1 h-1.5" />
                              <span className="text-[10px] text-muted-foreground">{modCompleted}/{modSteps}</span>
                            </div>
                          </div>
                          <ChevronDown className={`h-5 w-5 text-muted-foreground transition-transform shrink-0 ${isOpen ? 'rotate-180' : ''}`} />
                        </div>
                      </CollapsibleTrigger>

                      <CollapsibleContent>
                        <div className="border-t border-border/30">
                          {mod.steps.map((step, si) => {
                            const stepKey = `${currentTrack.role}-${mi}-${si}`;
                            const done = completedSteps.has(stepKey);
                            const StIcon = step.icon;

                            return (
                              <div key={si} className={`flex items-start gap-3 px-4 sm:px-6 py-4 border-b border-border/15 last:border-b-0 transition-colors ${done ? 'bg-emerald-50/40 dark:bg-emerald-950/10' : ''}`}>
                                <button
                                  onClick={() => toggleStep(stepKey)}
                                  className="shrink-0 mt-0.5"
                                  aria-label={done ? 'Mark incomplete' : 'Mark complete'}
                                >
                                  {done ? (
                                    <CheckCircle2 className="h-6 w-6 text-emerald-500" />
                                  ) : (
                                    <Circle className="h-6 w-6 text-border hover:text-primary transition-colors" />
                                  )}
                                </button>
                                <div className="flex-1 min-w-0">
                                  <div className="flex items-center gap-2 mb-0.5">
                                    <StIcon className="h-4 w-4 text-primary/70 shrink-0" />
                                    <h4 className={`text-sm font-semibold ${done ? 'text-muted-foreground line-through' : 'text-foreground'}`}>
                                      {step.title}
                                    </h4>
                                  </div>
                                  <div className="ml-6 space-y-1.5">
                                    <div className="flex items-start gap-1.5">
                                      <ChevronRight className="h-3.5 w-3.5 text-primary mt-0.5 shrink-0" />
                                      <p className="text-sm font-medium text-primary/90">{step.action}</p>
                                    </div>
                                    <p className="text-xs text-muted-foreground leading-relaxed">{step.detail}</p>
                                    {step.tip && (
                                      <div className="flex items-start gap-1.5 mt-2 px-2.5 py-1.5 rounded-lg bg-amber-50 dark:bg-amber-950/20 border border-amber-200/50 dark:border-amber-800/30">
                                        <Star className="h-3.5 w-3.5 text-amber-500 mt-0.5 shrink-0" />
                                        <p className="text-xs text-amber-800 dark:text-amber-300">{step.tip}</p>
                                      </div>
                                    )}
                                  </div>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </CollapsibleContent>
                    </Card>
                  </Collapsible>
                );
              })}
            </div>
          </div>
        )}

        {/* Bottom CTA */}
        <div className="text-center py-6 space-y-3 border-t border-border/30">
          <p className="text-muted-foreground text-sm">
            Still have questions? Your BCBA or administrator can help.
          </p>
          <div className="flex items-center justify-center gap-3">
            <Button variant="outline" onClick={() => navigate('/tour')} className="gap-1.5">
              <ArrowLeft className="h-4 w-4" />
              Back to Tour
            </Button>
            <Button onClick={() => navigate('/login')} className="gap-1.5">
              <LogIn className="h-4 w-4" />
              Sign In
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FAQTutorial;
